"""
expand_macro_events_v2.py
=========================
PHÂN TÍCH ĐẦY ĐỦ - CÁC KỊCH BẢN KINH TẾ CÒN THIẾU CHO SIMULATION VIỆT NAM
Dựa trên deep research toàn diện (1975-2026) về lịch sử kinh tế 63 tỉnh thành

Phân loại sự kiện còn thiếu theo 12 nhóm:
  A. Chính sách vĩ mô & Thể chế (Policy/Institutional)
  B. Khủng hoảng tài chính & Tiền tệ (Financial Crises)
  C. Hiệp định thương mại bổ sung (Trade Agreements)
  D. Thiên tai còn thiếu (Natural Disasters)
  E. Đại dịch & Dịch bệnh động vật (Pandemics/Animal Diseases)
  F. Sự kiện FDI cụ thể theo tỉnh (Province-Specific FDI)
  G. Hạ tầng chiến lược (Strategic Infrastructure)
  H. Năng lượng & Tài nguyên (Energy & Resources)
  I. Nông nghiệp - Hàng hóa (Agriculture/Commodities)
  J. Địa chính trị ảnh hưởng trực tiếp (Direct Geopolitics)
  K. Thị trường tài chính nội địa (Domestic Financial Markets)
  L. Tỉnh thành cụ thể còn thiếu (Province-Specific Missing Events)

Nguồn dữ liệu đề xuất để cào/mapping:
  - GSO (gso.gov.vn) - Tổng cục Thống kê
  - World Bank Open Data (data.worldbank.org)
  - EM-DAT disaster database (emdat.be)
  - VASEP, MARD, MOIT portals
  - ADB Economic Outlook Vietnam
  - IMF Article IV Consultations Vietnam
  - Vietnam Investment Review (vir.com.vn)
  - OpenDevelopmentMekong (vietnam.opendevelopmentmekong.net)
  - VNDMA (nchmf.gov.vn) - thiên tai
  - Provincial portals (e.g. baobinhduong.vn, baodongnai.vn)
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "data"
JSON_PATH = DATA_DIR / "historical_economic_events.json"

# ============================================================
# A. CHÍNH SÁCH VĨ MÔ & THỂ CHẾ (còn thiếu)
# ============================================================
policy_events = [
    {
        "event_key": "us_embargo_lift_1994",
        "event_name": "US Lifts Trade Embargo on Vietnam",
        "event_name_vi": "Mỹ dỡ bỏ lệnh cấm vận thương mại",
        "event_type": "policy",
        "start_date": "1994-02-03",
        "end_date": "1995-07-11",
        "duration_months": 18,
        "severity": "extreme",
        "impact_gdp_pct": 2.0,
        "impact_tax_revenue_pct": 3.5,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 25.0,
        "affected_provinces": [],
        "affected_sectors": ["Xuất nhập khẩu", "FDI", "Tài chính", "Du lịch"],
        "scope": "national",
        "description_vi": "Clinton dỡ bỏ lệnh cấm vận 19 năm với Việt Nam (2/2/1994), mở ra cánh cửa hội nhập với nền kinh tế thế giới và thu hút dòng vốn FDI quốc tế ồ ạt đổ vào Việt Nam.",
        "source": "White House/Ministry of Finance"
    },
    {
        "event_key": "vietnam_asean_1995",
        "event_name": "Vietnam Joins ASEAN",
        "event_name_vi": "Việt Nam gia nhập ASEAN",
        "event_type": "trade_agreement",
        "start_date": "1995-07-28",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 1.2,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 12.0,
        "affected_provinces": [],
        "affected_sectors": ["Thương mại", "FDI", "Du lịch", "Dịch vụ"],
        "scope": "national",
        "description_vi": "Việt Nam trở thành thành viên ASEAN, phá vỡ thế cô lập khu vực, mở đường cho AFTA (Khu mậu dịch tự do ASEAN) và hàng loạt hiệp định song phương trong khu vực.",
        "source": "ASEAN Secretariat/MPI"
    },
    {
        "event_key": "us_vn_normalization_1995",
        "event_name": "US-Vietnam Diplomatic Normalization",
        "event_name_vi": "Bình thường hóa quan hệ ngoại giao Việt-Mỹ",
        "event_type": "policy",
        "start_date": "1995-07-11",
        "end_date": "2001-12-10",
        "duration_months": 77,
        "severity": "extreme",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 20.0,
        "affected_provinces": [],
        "affected_sectors": ["FDI", "Du lịch", "Xuất nhập khẩu"],
        "scope": "national",
        "description_vi": "Bình thường hóa quan hệ ngoại giao Mỹ-Việt là bước ngoặt lịch sử, đặt nền móng cho BTA 2001 và mở ra làn sóng FDI từ Mỹ vào Việt Nam.",
        "source": "US State Department"
    },
    {
        "event_key": "khoan_10_agricultural_reform_1988",
        "event_name": "Khoan 10 Household Agricultural Reform",
        "event_name_vi": "Khoán 10 - Cải cách nông nghiệp hộ gia đình",
        "event_type": "policy",
        "start_date": "1988-04-05",
        "end_date": "1993-12-31",
        "duration_months": 68,
        "severity": "extreme",
        "impact_gdp_pct": 3.5,
        "impact_tax_revenue_pct": 4.0,
        "impact_unemployment_pct": -2.5,
        "impact_cpi_pct": -20.0,
        "impact_fdi_pct": 0.0,
        "affected_provinces": [],
        "affected_sectors": ["Nông nghiệp", "Lúa gạo", "Chăn nuôi"],
        "scope": "national",
        "description_vi": "Nghị quyết 10/NQ-TW giao quyền sử dụng đất lâu dài cho hộ nông dân, xóa bỏ hợp tác xã nông nghiệp tập thể. Sản lượng lúa bùng nổ - Việt Nam từ nước nhập khẩu gạo thành xuất khẩu gạo lớn thứ hai thế giới chỉ trong vài năm.",
        "source": "Central Committee Resolution 10/GSO"
    },
    {
        "event_key": "land_law_1993",
        "event_name": "Land Law 1993 - Land Use Rights",
        "event_name_vi": "Luật Đất đai 1993 - Quyền sử dụng đất",
        "event_type": "policy",
        "start_date": "1993-07-15",
        "end_date": "2003-12-31",
        "duration_months": 125,
        "severity": "high",
        "impact_gdp_pct": 1.8,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 8.0,
        "affected_provinces": [],
        "affected_sectors": ["Bất động sản", "Nông nghiệp", "Xây dựng", "FDI"],
        "scope": "national",
        "description_vi": "Luật Đất đai 1993 lần đầu công nhận 5 quyền của người sử dụng đất (chuyển đổi, chuyển nhượng, thừa kế, thế chấp, cho thuê), tạo nền tảng pháp lý cho thị trường BĐS và thu hút đầu tư.",
        "source": "National Assembly"
    },
    {
        "event_key": "hyperinflation_pre_doi_moi_1980s",
        "event_name": "Pre-Doi Moi Hyperinflation Crisis",
        "event_name_vi": "Siêu lạm phát trước Đổi Mới (1980-1986)",
        "event_type": "financial_crisis",
        "start_date": "1980-01-01",
        "end_date": "1986-11-30",
        "duration_months": 83,
        "severity": "extreme",
        "impact_gdp_pct": -5.0,
        "impact_tax_revenue_pct": -10.0,
        "impact_unemployment_pct": 5.0,
        "impact_cpi_pct": 700.0,
        "impact_fdi_pct": 0.0,
        "affected_provinces": [],
        "affected_sectors": ["Nông nghiệp", "Sản xuất", "Thương mại"],
        "scope": "national",
        "description_vi": "Nền kinh tế kế hoạch hóa tập trung sụp đổ: lạm phát phi mã 700%+, thiếu lương thực trầm trọng, bao cấp tem phiếu. Chính cuộc khủng hoảng này buộc Đảng phải tiến hành Đổi Mới 1986.",
        "source": "World Bank/GSO historical records"
    },
    {
        "event_key": "enterprise_law_2000",
        "event_name": "Enterprise Law 2000 - Private Sector Boom",
        "event_name_vi": "Luật Doanh nghiệp 2000 - Bùng nổ kinh tế tư nhân",
        "event_type": "policy",
        "start_date": "2000-01-01",
        "end_date": "2005-12-31",
        "duration_months": 72,
        "severity": "high",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 3.0,
        "impact_unemployment_pct": -1.5,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["79", "01", "31", "48"],
        "affected_sectors": ["Dịch vụ", "Thương mại", "Sản xuất", "Bán lẻ"],
        "scope": "national",
        "description_vi": "Luật Doanh nghiệp 2000 xóa bỏ hàng trăm giấy phép con, tạo làn sóng thành lập doanh nghiệp tư nhân chưa từng có: chỉ trong 5 năm đầu có hơn 160.000 doanh nghiệp mới đăng ký.",
        "source": "Ministry of Planning and Investment"
    },
    {
        "event_key": "nuclear_power_cancel_2016",
        "event_name": "Ninh Thuan Nuclear Power Cancel",
        "event_name_vi": "Hủy dự án Điện hạt nhân Ninh Thuận",
        "event_type": "policy",
        "start_date": "2016-11-22",
        "end_date": "2020-12-31",
        "duration_months": 50,
        "severity": "medium",
        "impact_gdp_pct": -0.1,
        "impact_tax_revenue_pct": -0.3,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["58"],
        "affected_sectors": ["Năng lượng", "Xây dựng", "Năng lượng tái tạo"],
        "scope": "regional",
        "description_vi": "Quốc hội bỏ phiếu hủy dự án nhà máy điện hạt nhân Ninh Thuận 1 & 2 (vốn dự kiến 27 tỷ USD). Ninh Thuận sau đó chuyển hướng thành thủ đô năng lượng tái tạo của Việt Nam.",
        "source": "National Assembly"
    },
    {
        "event_key": "hanoi_admin_expansion_2008",
        "event_name": "Hanoi Administrative Expansion",
        "event_name_vi": "Mở rộng địa giới hành chính Hà Nội",
        "event_type": "policy",
        "start_date": "2008-08-01",
        "end_date": "2015-12-31",
        "duration_months": 89,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["01"],
        "affected_sectors": ["Bất động sản", "Xây dựng", "Nông nghiệp", "Hạ tầng đô thị"],
        "scope": "regional",
        "description_vi": "Hà Nội sáp nhập tỉnh Hà Tây và một số huyện khác, tăng diện tích gấp 3 lần. Cú hích bất động sản khổng lồ vùng Tây Hà Nội, đồng thời kéo thêm hàng triệu lao động nông nghiệp vào đô thị.",
        "source": "National Assembly Resolution 15/2008"
    },
    {
        "event_key": "anti_china_riots_2014",
        "event_name": "Anti-China Riots (HD-981 Crisis)",
        "event_name_vi": "Biểu tình bài Trung (Vụ giàn khoan HD-981)",
        "event_type": "geopolitics",
        "start_date": "2014-05-13",
        "end_date": "2014-06-30",
        "duration_months": 2,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": -8.0,
        "affected_provinces": ["75", "74", "79", "42"],
        "affected_sectors": ["FDI", "Sản xuất", "Du lịch", "Dệt may"],
        "scope": "regional",
        "description_vi": "Phản ứng với việc Trung Quốc đặt giàn khoan HD-981 vào vùng biển Việt Nam, cuộc biểu tình bùng phát tại Bình Dương, Đồng Nai, Hà Tĩnh... gây thiệt hại cho hàng trăm nhà máy FDI, đặc biệt là doanh nghiệp Đài Loan, Trung Quốc, Hàn Quốc.",
        "source": "MPI/Government"
    },
    {
        "event_key": "us_arms_embargo_lift_2016",
        "event_name": "US Lifts Arms Embargo on Vietnam",
        "event_name_vi": "Mỹ dỡ bỏ lệnh cấm bán vũ khí",
        "event_type": "geopolitics",
        "start_date": "2016-05-23",
        "end_date": None,
        "duration_months": 60,
        "severity": "medium",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["01", "79"],
        "affected_sectors": ["FDI", "Quốc phòng", "Công nghệ cao", "Du lịch"],
        "scope": "national",
        "description_vi": "Obama dỡ bỏ hoàn toàn lệnh cấm vận vũ khí với Việt Nam, đánh dấu quan hệ chiến lược toàn diện và mở đường cho các hợp đồng quốc phòng, đồng thời thúc đẩy FDI Mỹ vào lĩnh vực công nghệ cao.",
        "source": "US State Department"
    },
    {
        "event_key": "vn_us_comprehensive_strategic_partnership_2023",
        "event_name": "Vietnam-US Comprehensive Strategic Partnership",
        "event_name_vi": "Đối tác Chiến lược Toàn diện Việt-Mỹ",
        "event_type": "geopolitics",
        "start_date": "2023-09-10",
        "end_date": None,
        "duration_months": 60,
        "severity": "extreme",
        "impact_gdp_pct": 1.0,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 15.0,
        "affected_provinces": ["01", "79", "31", "27", "24"],
        "affected_sectors": ["Bán dẫn", "Công nghệ cao", "FDI", "Giáo dục"],
        "scope": "national",
        "description_vi": "Biden và Tổng Bí thư Nguyễn Phú Trọng ký kết nâng cấp quan hệ lên Đối tác Chiến lược Toàn diện. Hàng loạt cam kết đầu tư từ Apple, Boeing, Nvidia, Amkor được công bố ngay sau đó, mở ra kỷ nguyên mới cho ngành bán dẫn.",
        "source": "Ministry of Foreign Affairs"
    },
    {
        "event_key": "ftse_emerging_market_upgrade_2025",
        "event_name": "Vietnam FTSE Emerging Market Upgrade",
        "event_name_vi": "Việt Nam được nâng hạng Thị trường Mới nổi FTSE",
        "event_type": "policy",
        "start_date": "2025-10-07",
        "end_date": None,
        "duration_months": 36,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 8.0,
        "affected_provinces": ["01", "79"],
        "affected_sectors": ["Tài chính ngân hàng", "Chứng khoán", "FDI", "Bất động sản"],
        "scope": "national",
        "description_vi": "FTSE Russell chính thức công bố nâng hạng Việt Nam từ Thị trường Biên (Frontier) lên Thị trường Mới nổi (Emerging Market) từ tháng 9/2026, kỳ vọng thu hút thêm 5-8 tỷ USD vốn đầu tư thụ động quốc tế.",
        "source": "FTSE Russell/HNX/HOSE"
    },
]

# ============================================================
# B. KHỦNG HOẢNG TÀI CHÍNH & THỊ TRƯỜNG (còn thiếu)
# ============================================================
financial_events = [
    {
        "event_key": "hose_launch_2000",
        "event_name": "Ho Chi Minh Stock Exchange Launch",
        "event_name_vi": "Sở Giao dịch Chứng khoán TP.HCM ra đời",
        "event_type": "policy",
        "start_date": "2000-07-28",
        "end_date": "2005-12-31",
        "duration_months": 65,
        "severity": "medium",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": -0.1,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 1.0,
        "affected_provinces": ["79"],
        "affected_sectors": ["Tài chính ngân hàng", "Dịch vụ", "Công ty đại chúng"],
        "scope": "national",
        "description_vi": "Sở giao dịch chứng khoán đầu tiên của Việt Nam đi vào hoạt động với 2 mã CK đầu tiên (REE, SAM). Đặt nền móng cho kênh huy động vốn dài hạn của nền kinh tế.",
        "source": "SSC/HOSE"
    },
    {
        "event_key": "vnindex_bubble_2006_2007",
        "event_name": "VN-Index Stock Market Bubble",
        "event_name_vi": "Bong bóng Chứng khoán VN-Index 2006-2007",
        "event_type": "financial_crisis",
        "start_date": "2006-01-01",
        "end_date": "2008-03-31",
        "duration_months": 27,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 3.0,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["79", "01"],
        "affected_sectors": ["Tài chính ngân hàng", "Bất động sản", "Dịch vụ"],
        "scope": "national",
        "description_vi": "VN-Index tăng từ 300 điểm lên đỉnh 1.170 điểm (2/2007) rồi sụp đổ còn 235 điểm (cuối 2008). Hàng triệu nhà đầu tư cá nhân mất trắng, các ngân hàng tung tín dụng margin gây rủi ro hệ thống.",
        "source": "SSC/HOSE"
    },
    {
        "event_key": "npl_banking_reform_2012",
        "event_name": "NPL & Banking System Reform 2012-2015",
        "event_name_vi": "Cơ cấu lại ngân hàng & xử lý nợ xấu (VAMC)",
        "event_type": "financial_crisis",
        "start_date": "2012-01-01",
        "end_date": "2016-12-31",
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -2.0,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": -0.5,
        "impact_fdi_pct": -3.0,
        "affected_provinces": ["79", "01", "48"],
        "affected_sectors": ["Tài chính ngân hàng", "Bất động sản", "Xây dựng"],
        "scope": "national",
        "description_vi": "Nợ xấu toàn hệ thống ngân hàng leo lên 17-20% (theo số liệu thực tế), NHNN thành lập VAMC mua nợ xấu. Hàng loạt ngân hàng yếu kém bị sáp nhập hoặc mua lại với giá 0 đồng (GP Bank, OceanBank, CBBank).",
        "source": "State Bank of Vietnam"
    },
    {
        "event_key": "dong_devaluation_2015",
        "event_name": "VND Devaluation & Forex Reform 2015",
        "event_name_vi": "Phá giá VND & Cải cách tỷ giá 2015",
        "event_type": "financial_crisis",
        "start_date": "2015-08-12",
        "end_date": "2016-06-30",
        "duration_months": 11,
        "severity": "medium",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": -2.0,
        "affected_provinces": [],
        "affected_sectors": ["Xuất nhập khẩu", "Tài chính ngân hàng", "Doanh nghiệp vay ngoại tệ"],
        "scope": "national",
        "description_vi": "SBV phá giá VND thêm 3% và chuyển từ tỷ giá cố định sang tỷ giá trung tâm linh hoạt hàng ngày (sau khi Trung Quốc phá giá CNY). Tạo ra bất ổn ngắn hạn nhưng mang lại hệ thống tỷ giá minh bạch hơn.",
        "source": "State Bank of Vietnam"
    },
    {
        "event_key": "corporate_bond_crisis_2022",
        "event_name": "Corporate Bond Market Freeze 2022",
        "event_name_vi": "Khủng hoảng Trái phiếu Doanh nghiệp 2022",
        "event_type": "financial_crisis",
        "start_date": "2022-04-01",
        "end_date": "2023-12-31",
        "duration_months": 21,
        "severity": "high",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -2.5,
        "impact_unemployment_pct": 0.6,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": -1.5,
        "affected_provinces": ["79", "01"],
        "affected_sectors": ["Bất động sản", "Tài chính ngân hàng", "Xây dựng"],
        "scope": "national",
        "description_vi": "Sau vụ bắt Chủ tịch Tân Hoàng Minh và Vạn Thịnh Phát, thị trường TPDN đóng băng hoàn toàn. Dư nợ TPDN 1.5 triệu tỷ đồng gặp áp lực đáo hạn, nhiều BĐS nhà phát triển mất thanh khoản.",
        "source": "Ministry of Finance/SSC"
    },
    {
        "event_key": "evn_financial_crisis_2022_2023",
        "event_name": "EVN Power Utility Financial Crisis",
        "event_name_vi": "Khủng hoảng tài chính EVN - thiếu điện",
        "event_type": "infrastructure_shock",
        "start_date": "2022-01-01",
        "end_date": "2024-06-30",
        "duration_months": 30,
        "severity": "high",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": -3.0,
        "affected_provinces": ["19", "27", "24", "26", "01", "31"],
        "affected_sectors": ["Sản xuất công nghiệp", "Năng lượng", "FDI"],
        "scope": "national",
        "description_vi": "EVN lỗ tích lũy hơn 50.000 tỷ đồng do giá mua điện tăng mạnh nhưng giá bán bị kìm. Tình trạng cắt điện diện rộng tại miền Bắc (5-6/2023) gây thiệt hại hàng nghìn tỷ cho khu công nghiệp, làm FDI lo ngại về an ninh năng lượng.",
        "source": "EVN/Ministry of Industry and Trade"
    },
    {
        "event_key": "renewable_fit_retroactive_dispute_2024",
        "event_name": "Renewable Energy FIT Retroactive Price Cut",
        "event_name_vi": "Tranh chấp cắt giảm giá FIT điện tái tạo hồi tố",
        "event_type": "policy",
        "start_date": "2024-01-01",
        "end_date": None,
        "duration_months": 36,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": -4.0,
        "affected_provinces": ["58", "60", "72", "45", "64"],
        "affected_sectors": ["Năng lượng tái tạo", "FDI", "Tài chính ngân hàng"],
        "scope": "regional",
        "description_vi": "Chính phủ yêu cầu EVN thu hồi khoản chênh lệch giá mua điện FIT (173 dự án, tổng 13.837 MW), có thể cắt giảm doanh thu 25-46%. Nguy cơ phá sản hàng loạt DN điện tái tạo, ảnh hưởng nghiêm trọng niềm tin nhà đầu tư.",
        "source": "IEEFA/Ministry of Industry and Trade"
    },
]

# ============================================================
# C. HIỆP ĐỊNH THƯƠNG MẠI BỔ SUNG
# ============================================================
trade_events = [
    {
        "event_key": "vkfta_2015",
        "event_name": "Vietnam-Korea FTA (VKFTA)",
        "event_name_vi": "Hiệp định Thương mại Tự do Việt-Hàn (VKFTA)",
        "event_type": "trade_agreement",
        "start_date": "2015-12-20",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.0,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 12.0,
        "affected_provinces": ["27", "19", "31", "79"],
        "affected_sectors": ["Sản xuất điện tử", "Dệt may", "Thủy sản", "FDI Hàn Quốc"],
        "scope": "national",
        "description_vi": "VKFTA thúc đẩy dòng vốn FDI Hàn Quốc vào Việt Nam (hiện chiếm 18% tổng FDI), tạo điều kiện cho Samsung, LG, Lotte, Hyundai mở rộng đầu tư. Hàn Quốc trở thành đối tác thương mại số 1 của Việt Nam.",
        "source": "MOIT"
    },
    {
        "event_key": "rcep_2022",
        "event_name": "RCEP Enters into Force for Vietnam",
        "event_name_vi": "Hiệp định RCEP có hiệu lực với Việt Nam",
        "event_type": "trade_agreement",
        "start_date": "2022-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.4,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.6,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 8.0,
        "affected_provinces": [],
        "affected_sectors": ["Sản xuất", "Nông nghiệp", "Dệt may", "Xuất nhập khẩu"],
        "scope": "national",
        "description_vi": "RCEP - hiệp định thương mại khu vực lớn nhất thế giới (30% GDP toàn cầu) - có hiệu lực cho Việt Nam, tạo ra thị trường 2.2 tỷ người với thuế quan ưu đãi, đặc biệt trong chuỗi cung ứng nội khối ASEAN-Trung Quốc-Nhật-Hàn.",
        "source": "MOIT/ASEAN Secretariat"
    },
    {
        "event_key": "ukvfta_2021",
        "event_name": "UK-Vietnam FTA (UKVFTA)",
        "event_name_vi": "Hiệp định Thương mại Tự do Việt Nam-Anh (UKVFTA)",
        "event_type": "trade_agreement",
        "start_date": "2021-05-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "medium",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 0.8,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": 2.0,
        "affected_provinces": [],
        "affected_sectors": ["Dệt may", "Da giày", "Thủy sản", "Dịch vụ"],
        "scope": "national",
        "description_vi": "UKVFTA duy trì ưu đãi thuế quan với Anh sau Brexit (thay thế EVFTA đối với UK), bảo vệ $6.6 tỷ kim ngạch xuất khẩu Việt-Anh hàng năm.",
        "source": "MOIT"
    },
    {
        "event_key": "antidumping_shrimp_us_2004",
        "event_name": "US Anti-Dumping Shrimp Tariffs",
        "event_name_vi": "Mỹ áp thuế chống bán phá giá tôm Việt Nam",
        "event_type": "trade_war",
        "start_date": "2004-02-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["96", "95", "94", "92", "91", "89"],
        "affected_sectors": ["Thủy sản", "Chế biến thủy sản", "Nông nghiệp"],
        "scope": "regional",
        "description_vi": "Bộ Thương mại Mỹ áp thuế chống bán phá giá tôm Việt Nam (0.09-25.76%), gây thiệt hại nghiêm trọng cho ngành tôm ĐBSCL, đặc biệt Cà Mau, Bạc Liêu, Sóc Trăng - thị trường xuất khẩu chính.",
        "source": "VASEP/US DOC"
    },
    {
        "event_key": "antidumping_catfish_us_2003",
        "event_name": "US Anti-Dumping Catfish (Tra Fish) Case",
        "event_name_vi": "Mỹ áp thuế chống bán phá giá cá Tra, Ba Sa",
        "event_type": "trade_war",
        "start_date": "2003-07-23",
        "end_date": None,
        "duration_months": 240,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["89", "87"],
        "affected_sectors": ["Thủy sản", "Nuôi trồng thủy sản", "Chế biến thực phẩm"],
        "scope": "regional",
        "description_vi": "DOC Mỹ áp thuế 36.84-63.88% với cá tra/ba sa Việt Nam sau vận động của ngành da trơn Mỹ. Buộc Việt Nam đa dạng hóa thị trường sang EU, Trung Đông - hành trình pháp lý kéo dài 20+ năm.",
        "source": "VASEP/US DOC"
    },
]

# ============================================================
# D. THIÊN TAI CÒN THIẾU
# ============================================================
disaster_events = [
    {
        "event_key": "sars_2003",
        "event_name": "SARS Outbreak - Vietnam First to Contain",
        "event_name_vi": "Dịch SARS - Việt Nam đầu tiên kiểm soát",
        "event_type": "pandemic",
        "start_date": "2003-02-26",
        "end_date": "2003-04-28",
        "duration_months": 2,
        "severity": "medium",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": -5.0,
        "affected_provinces": ["01", "79"],
        "affected_sectors": ["Du lịch", "Hàng không", "Dịch vụ", "Y tế"],
        "scope": "national",
        "description_vi": "Việt Nam là quốc gia đầu tiên trên thế giới được WHO công nhận kiểm soát thành công SARS (28/4/2003) - được ca ngợi là hình mẫu phòng dịch. Tuy nhiên, du lịch và dịch vụ thiệt hại nặng trong 2 tháng bùng phát.",
        "source": "WHO/Ministry of Health"
    },
    {
        "event_key": "avian_flu_h5n1_2004",
        "event_name": "H5N1 Bird Flu Epidemic 2004-2005",
        "event_name_vi": "Đại dịch Cúm gia cầm H5N1 2004-2005",
        "event_type": "pandemic",
        "start_date": "2003-12-01",
        "end_date": "2005-12-31",
        "duration_months": 25,
        "severity": "high",
        "impact_gdp_pct": -0.4,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 2.5,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["01", "36", "37", "34", "35", "30", "33", "82", "83", "87", "89", "91", "96"],
        "affected_sectors": ["Chăn nuôi gia cầm", "Nông nghiệp", "Du lịch"],
        "scope": "national",
        "description_vi": "H5N1 bùng phát tại 64/64 tỉnh thành, hơn 40 triệu con gia cầm bị tiêu hủy. Việt Nam là ổ dịch H5N1 lớn nhất thế giới 2004, gây thiệt hại hàng nghìn tỷ đồng cho ngành chăn nuôi và đẩy giá thực phẩm tăng mạnh.",
        "source": "Ministry of Agriculture/WHO"
    },
    {
        "event_key": "h1n1_swine_flu_2009",
        "event_name": "H1N1 Swine Flu Pandemic 2009",
        "event_name_vi": "Đại dịch Cúm A/H1N1 2009",
        "event_type": "pandemic",
        "start_date": "2009-05-01",
        "end_date": "2010-06-30",
        "duration_months": 14,
        "severity": "medium",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["79", "01", "48"],
        "affected_sectors": ["Du lịch", "Hàng không", "Chăn nuôi"],
        "scope": "national",
        "description_vi": "Hơn 10.000 ca H1N1 tại Việt Nam. Tác động kinh tế nhẹ hơn SARS do đặc tính ít nguy hiểm hơn, nhưng du lịch và hàng không gặp khó khăn ngắn hạn.",
        "source": "Ministry of Health/WHO"
    },
    {
        "event_key": "shrimp_ems_disease_2012",
        "event_name": "Shrimp EMS (AHPND) Disease Crisis",
        "event_name_vi": "Dịch bệnh tôm EMS/AHPND ĐBSCL 2012-2014",
        "event_type": "pandemic",
        "start_date": "2010-01-01",
        "end_date": "2015-12-31",
        "duration_months": 72,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.8,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["96", "95", "94", "91", "89"],
        "affected_sectors": ["Thủy sản", "Nuôi trồng thủy sản", "Chế biến"],
        "scope": "regional",
        "description_vi": "Hội chứng tôm chết sớm (EMS/AHPND) do vi khuẩn Vibrio parahaemolyticus tấn công Cà Mau, Bạc Liêu, Sóc Trăng... gây tỷ lệ chết 100% trong 20-30 ngày. Thiệt hại ước tính 60+ triệu USD, sản lượng giảm 50%.",
        "source": "MARD/VASEP/FAO"
    },
    {
        "event_key": "typhoon_mirinae_2009",
        "event_name": "Typhoon Mirinae 2009",
        "event_name_vi": "Bão số 11 (Mirinae) 2009",
        "event_type": "natural_disaster",
        "start_date": "2009-11-02",
        "end_date": "2009-11-10",
        "duration_months": 1,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.7,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.8,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["52", "54", "56"],
        "affected_sectors": ["Nông nghiệp", "Cơ sở hạ tầng", "Du lịch"],
        "scope": "regional",
        "description_vi": "Bão Mirinae đổ bộ vào Phú Yên-Bình Định với sức gió giật cấp 13-14, gây thiệt hại hơn 10.000 tỷ đồng, phá hủy hàng nghìn tàu thuyền đánh cá và nhà dân.",
        "source": "VNDMA"
    },
    {
        "event_key": "typhoon_nari_2013",
        "event_name": "Typhoon Nari 2013",
        "event_name_vi": "Bão số 11 (Nari) 2013",
        "event_type": "natural_disaster",
        "start_date": "2013-10-14",
        "end_date": "2013-10-25",
        "duration_months": 1,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.6,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 0.6,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["46", "48", "49"],
        "affected_sectors": ["Du lịch", "Nông nghiệp", "Cơ sở hạ tầng"],
        "scope": "regional",
        "description_vi": "Bão Nari đổ bộ thẳng vào Thừa Thiên Huế - Đà Nẵng, gây ngập lụt nghiêm trọng tại đô thị và thiệt hại lớn cho sản xuất nông nghiệp vùng thấp trũng.",
        "source": "VNDMA"
    },
    {
        "event_key": "typhoon_doksuri_2023",
        "event_name": "Typhoon Doksuri 2023",
        "event_name_vi": "Bão số 3 (Doksuri) 2023 và lũ lịch sử",
        "event_type": "natural_disaster",
        "start_date": "2023-07-26",
        "end_date": "2023-08-31",
        "duration_months": 1,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["01", "22", "31", "24", "25", "10"],
        "affected_sectors": ["Nông nghiệp", "Lâm nghiệp", "Sản xuất công nghiệp"],
        "scope": "regional",
        "description_vi": "Doksuri gây mưa lũ lịch sử tại Bắc Bộ, ngập lụt diện rộng ở Hà Nội, Quảng Ninh, Hải Phòng. Thiệt hại đáng kể tuy nhiên nhỏ hơn Yagi 2024.",
        "source": "VNDMA"
    },
    {
        "event_key": "northern_mountain_floods_2018",
        "event_name": "Northern Mountain Flash Floods 2018",
        "event_name_vi": "Lũ quét thảm khốc miền núi phía Bắc 2018",
        "event_type": "natural_disaster",
        "start_date": "2018-06-01",
        "end_date": "2018-09-30",
        "duration_months": 4,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.4,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["12", "15", "02", "14", "17"],
        "affected_sectors": ["Nông nghiệp", "Giao thông", "Nhà ở"],
        "scope": "regional",
        "description_vi": "Mưa lũ, lũ quét, sạt lở liên tiếp tại Lai Châu, Yên Bái, Hà Giang, Sơn La, Hòa Bình. Hàng trăm người chết và mất tích, hàng nghìn tỷ thiệt hại hạ tầng giao thông, trường học, nhà dân.",
        "source": "VNDMA/Ministry of Agriculture"
    },
    {
        "event_key": "rao_trang_landslide_2020",
        "event_name": "Rao Trang 3 Hydropower Landslide 2020",
        "event_name_vi": "Sạt lở Rao Trăng 3 - Trà Leng 2020",
        "event_type": "natural_disaster",
        "start_date": "2020-10-17",
        "end_date": "2020-11-30",
        "duration_months": 2,
        "severity": "high",
        "impact_gdp_pct": -0.1,
        "impact_tax_revenue_pct": -0.3,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["46", "49"],
        "affected_sectors": ["Thủy điện", "Lâm nghiệp", "Cơ sở hạ tầng"],
        "scope": "regional",
        "description_vi": "Sạt lở đất tại trạm kiểm lâm tiểu khu 67 và thủy điện Rao Trăng 3 (Thừa Thiên Huế) và Trà Leng (Quảng Nam) trong mưa lũ lịch sử, khiến hàng chục người thiệt mạng bao gồm cả lực lượng cứu hộ.",
        "source": "VNDMA/Government"
    },
    {
        "event_key": "mekong_drought_2019_2020",
        "event_name": "Mekong Drought & Salinity 2019-2020",
        "event_name_vi": "Hạn mặn ĐBSCL 2019-2020 (nghiêm trọng hơn 2016)",
        "event_type": "natural_disaster",
        "start_date": "2019-11-01",
        "end_date": "2020-06-30",
        "duration_months": 8,
        "severity": "extreme",
        "impact_gdp_pct": -0.6,
        "impact_tax_revenue_pct": -1.2,
        "impact_unemployment_pct": 1.0,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["80", "82", "83", "84", "86", "87", "89", "91", "92", "93", "94", "95", "96"],
        "affected_sectors": ["Nông nghiệp", "Thủy sản", "Chế biến thực phẩm", "Nước sinh hoạt"],
        "scope": "regional",
        "description_vi": "Đợt hạn mặn 2019-2020 được đánh giá còn khốc liệt hơn kỷ lục 2016. Dòng chảy Mekong đạt mức thấp lịch sử, nước mặn xâm nhập sâu 60-90km, thiệt hại lúa và cây ăn trái toàn vùng hơn 39.000 tỷ đồng.",
        "source": "MARD/Mekong River Commission"
    },
    {
        "event_key": "hydropower_drought_2019",
        "event_name": "Northern Vietnam Hydropower Drought 2019-2022",
        "event_name_vi": "Hạn hán thủy điện miền Bắc - nguy cơ thiếu điện",
        "event_type": "natural_disaster",
        "start_date": "2019-08-01",
        "end_date": "2023-07-31",
        "duration_months": 48,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.8,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["01", "27", "24", "26", "19"],
        "affected_sectors": ["Năng lượng", "Sản xuất công nghiệp", "FDI"],
        "scope": "regional",
        "description_vi": "Mực nước hồ chứa thủy điện toàn miền Bắc xuống mức thấp kỷ lục nhiều năm liên tiếp. Đỉnh điểm 5-6/2023 EVN cắt điện luân phiên tại các khu công nghiệp Bắc Ninh, Hải Dương, Hưng Yên - thiệt hại nghìn tỷ cho FDI.",
        "source": "EVN/Ministry of Industry and Trade"
    },
    {
        "event_key": "typhoon_bualoi_2025",
        "event_name": "Typhoon Bualoi 2025",
        "event_name_vi": "Bão Bualoi và chuỗi thiên tai 2025",
        "event_type": "natural_disaster",
        "start_date": "2025-05-01",
        "end_date": "2025-12-31",
        "duration_months": 8,
        "severity": "extreme",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.4,
        "impact_cpi_pct": 1.2,
        "impact_fdi_pct": -1.5,
        "affected_provinces": ["01", "22", "31", "24", "25", "40", "44", "45", "46"],
        "affected_sectors": ["Nông nghiệp", "Lâm nghiệp", "Thủy sản", "Cơ sở hạ tầng"],
        "scope": "regional",
        "description_vi": "12 cơn bão và ATNĐ trong năm 2025, trong đó Bualoi gây thiệt hại nghiêm trọng nhất: 420 người chết/mất tích, 545.352 ha lúa bị ngập, 1.032 km đê bao bị phá vỡ theo báo cáo UN Joint Response Plan.",
        "source": "VNDMA/UN Vietnam"
    },
]

# ============================================================
# E. FDI CỤ THỂ THEO TỈNH - THIẾU NHIỀU
# ============================================================
fdi_events = [
    {
        "event_key": "samsung_bac_ninh_2008",
        "event_name": "Samsung First Vietnam Factory - Bac Ninh",
        "event_name_vi": "Samsung mở nhà máy đầu tiên tại Bắc Ninh (SEV)",
        "event_type": "growth",
        "start_date": "2008-03-01",
        "end_date": "2014-12-31",
        "duration_months": 81,
        "severity": "extreme",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 4.0,
        "impact_unemployment_pct": -1.2,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 8.0,
        "affected_provinces": ["27"],
        "affected_sectors": ["Sản xuất điện tử", "Công nghệ cao", "Dịch vụ hỗ trợ"],
        "scope": "regional",
        "description_vi": "Samsung Electronics Vietnam (SEV) đầu tư 670 triệu USD tại KCN Yên Phong, Bắc Ninh. Đây là nhà máy điện thoại Samsung đầu tiên tại Việt Nam - điểm khởi đầu biến Việt Nam thành cứ điểm SX smartphone lớn nhất Samsung toàn cầu.",
        "source": "Samsung/MPI"
    },
    {
        "event_key": "lg_hai_phong_2015",
        "event_name": "LG Electronics & Display Complex Hai Phong",
        "event_name_vi": "Tổ hợp LG Electronics & Display tại Hải Phòng",
        "event_type": "growth",
        "start_date": "2015-05-01",
        "end_date": "2021-12-31",
        "duration_months": 79,
        "severity": "extreme",
        "impact_gdp_pct": 1.2,
        "impact_tax_revenue_pct": 3.5,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 6.5,
        "affected_provinces": ["31"],
        "affected_sectors": ["Sản xuất điện tử", "Màn hình", "Điện thoại"],
        "scope": "regional",
        "description_vi": "LG Electronics và LG Display đầu tư tổng cộng hơn 3 tỷ USD tại KCN Tràng Duệ, Hải Phòng - sản xuất smartphone, màn hình OLED, linh kiện điện tử. Biến Hải Phòng thành hub điện tử lớn thứ hai Việt Nam.",
        "source": "Hai Phong Portal/MPI"
    },
    {
        "event_key": "foxconn_bac_giang_2020",
        "event_name": "Foxconn & Apple Supply Chain Bac Giang Expansion",
        "event_name_vi": "Foxconn mở rộng - Bắc Giang vào chuỗi cung ứng Apple",
        "event_type": "growth",
        "start_date": "2020-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "extreme",
        "impact_gdp_pct": 2.5,
        "impact_tax_revenue_pct": 5.0,
        "impact_unemployment_pct": -2.0,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 12.0,
        "affected_provinces": ["24"],
        "affected_sectors": ["Sản xuất điện tử", "Công nghệ cao", "Logistics"],
        "scope": "regional",
        "description_vi": "Foxconn đầu tư 1.5 tỷ USD vào Bắc Giang (KCN Vân Trung, Quang Châu), kéo theo Luxshare, Pegatron, GoerTek - toàn bộ chuỗi cung ứng iPad, AirPods, Apple Watch. Bắc Giang từ tỉnh vải thiều thành tỉnh xuất khẩu điện tử lớn nhất Việt Nam.",
        "source": "Bac Giang Portal/MPI"
    },
    {
        "event_key": "amkor_semiconductor_bac_ninh_2023",
        "event_name": "Amkor Semiconductor Packaging Bac Ninh",
        "event_name_vi": "Amkor đầu tư đóng gói bán dẫn tại Bắc Ninh",
        "event_type": "growth",
        "start_date": "2023-10-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["27"],
        "affected_sectors": ["Bán dẫn", "Công nghệ cao", "Đóng gói chip"],
        "scope": "regional",
        "description_vi": "Amkor Technology (Mỹ) khánh thành nhà máy đóng gói và kiểm thử chip 1.6 tỷ USD tại Yên Phong II, Bắc Ninh - nhà máy bán dẫn tiên tiến nhất Đông Nam Á, sản xuất chip cho Apple, Samsung, Qualcomm.",
        "source": "MPI/Bac Ninh Portal"
    },
    {
        "event_key": "hyundai_thanh_cong_ninh_binh",
        "event_name": "Hyundai Thanh Cong Auto Plant Ninh Binh",
        "event_name_vi": "Nhà máy ô tô Hyundai Thành Công tại Ninh Bình",
        "event_type": "growth",
        "start_date": "2012-01-01",
        "end_date": "2020-12-31",
        "duration_months": 108,
        "severity": "high",
        "impact_gdp_pct": 0.6,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["37"],
        "affected_sectors": ["Sản xuất ô tô", "Công nghiệp phụ trợ"],
        "scope": "regional",
        "description_vi": "Nhà máy lắp ráp ô tô Hyundai TC Motor tại KCN Gián Khẩu, Ninh Bình góp phần biến Ninh Bình thành trung tâm công nghiệp ô tô Bắc Trung Bộ, bên cạnh VSIP III và Hoàng Long.",
        "source": "Ninh Binh Portal"
    },
    {
        "event_key": "posco_steel_ba_ria_vung_tau",
        "event_name": "POSCO Steel Complex Ba Ria Vung Tau",
        "event_name_vi": "Khu liên hợp thép POSCO tại Bà Rịa - Vũng Tàu",
        "event_type": "growth",
        "start_date": "2009-01-01",
        "end_date": "2016-12-31",
        "duration_months": 96,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["77"],
        "affected_sectors": ["Thép", "Công nghiệp nặng", "Cảng biển"],
        "scope": "regional",
        "description_vi": "Tổ hợp sản xuất thép cán nguội của POSCO (Hàn Quốc) tại Phú Mỹ, Bà Rịa-Vũng Tàu, đáp ứng nhu cầu thép cán cho ngành sản xuất và xây dựng trong nước.",
        "source": "Ba Ria Vung Tau Portal"
    },
    {
        "event_key": "luxshare_nghe_an_2020",
        "event_name": "Luxshare (Apple Supplier) Nghe An",
        "event_name_vi": "Luxshare ICT - nhà cung cấp Apple tại Nghệ An",
        "event_type": "growth",
        "start_date": "2020-06-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.0,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 4.0,
        "affected_provinces": ["40"],
        "affected_sectors": ["Sản xuất điện tử", "Công nghệ cao"],
        "scope": "regional",
        "description_vi": "Luxshare ICT (Trung Quốc, đối tác chiến lược Apple) đầu tư KCN VSIP Nghệ An, đưa Nghệ An vào chuỗi cung ứng Apple toàn cầu. Cùng với Foxconn, đây là bước đưa Apple supply chain ra khỏi Bắc Ninh-Bắc Giang.",
        "source": "Nghe An Portal/MPI"
    },
    {
        "event_key": "lego_factory_opening_2025",
        "event_name": "LEGO Factory Grand Opening Binh Duong",
        "event_name_vi": "Khánh thành nhà máy LEGO xanh tại Bình Dương",
        "event_type": "growth",
        "start_date": "2025-04-09",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.8,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["74"],
        "affected_sectors": ["Sản xuất đồ chơi", "Năng lượng tái tạo", "FDI xanh"],
        "scope": "regional",
        "description_vi": "Nhà máy LEGO carbon-neutral đầu tiên tại Đông Nam Á khánh thành tại VSIP III Bình Dương với 12.400 tấm pin mặt trời, 62 sân bóng đá, 4.000 công nhân. Mô hình FDI xanh tiêu chuẩn cao nhất Việt Nam.",
        "source": "LEGO Group/Government"
    },
    {
        "event_key": "vinfast_nasdaq_ipo_2023",
        "event_name": "VinFast NASDAQ IPO",
        "event_name_vi": "VinFast niêm yết trên Sàn chứng khoán NASDAQ",
        "event_type": "growth",
        "start_date": "2023-08-15",
        "end_date": None,
        "duration_months": 24,
        "severity": "high",
        "impact_gdp_pct": 0.2,
        "impact_tax_revenue_pct": 0.3,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["31", "79"],
        "affected_sectors": ["Sản xuất ô tô điện", "Công nghệ", "Tài chính"],
        "scope": "national",
        "description_vi": "VinFast lên sàn NASDAQ qua thương vụ SPAC, vốn hóa đạt đỉnh 85 tỷ USD (lớn hơn Ford, GM thời điểm đó). Sự kiện đặt Việt Nam lên bản đồ xe điện toàn cầu và tạo sức hút với FDI xanh công nghệ cao.",
        "source": "VinFast/NASDAQ"
    },
]

# ============================================================
# F. HẠ TẦNG CHIẾN LƯỢC CÒN THIẾU
# ============================================================
infrastructure_events = [
    {
        "event_key": "cat_linh_metro_2021",
        "event_name": "Cat Linh - Ha Dong Metro Line 2A Opening",
        "event_name_vi": "Khai trương Tuyến Metro Cát Linh - Hà Đông",
        "event_type": "growth",
        "start_date": "2021-11-06",
        "end_date": None,
        "duration_months": 60,
        "severity": "medium",
        "impact_gdp_pct": 0.2,
        "impact_tax_revenue_pct": 0.4,
        "impact_unemployment_pct": -0.1,
        "impact_cpi_pct": -0.1,
        "impact_fdi_pct": 0.5,
        "affected_provinces": ["01"],
        "affected_sectors": ["Giao thông đô thị", "Bất động sản", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "Tuyến đường sắt đô thị đầu tiên của Hà Nội sau 10 năm xây dựng (13 km, vốn ODA Trung Quốc 18.000 tỷ đồng). Mở ra kỷ nguyên giao thông công cộng hiện đại và hình thành trục BĐS mới Hà Đông.",
        "source": "Ministry of Transport"
    },
    {
        "event_key": "hcmc_metro_line1_2024",
        "event_name": "HCMC Metro Line 1 Opening",
        "event_name_vi": "Khai trương Metro TP.HCM Tuyến số 1",
        "event_type": "growth",
        "start_date": "2024-12-22",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": -0.1,
        "impact_fdi_pct": 1.5,
        "affected_provinces": ["79"],
        "affected_sectors": ["Giao thông đô thị", "Bất động sản", "Dịch vụ đô thị"],
        "scope": "regional",
        "description_vi": "Tuyến Metro số 1 Bến Thành - Suối Tiên (19.7km, ODA Nhật Bản) khai trương sau 16 năm xây dựng, kết nối TP.HCM với Bình Dương. Tạo trục đô thị hóa mới dọc hành lang phía Đông.",
        "source": "HCMC Metro Management/Ministry of Transport"
    },
    {
        "event_key": "north_south_expressway_2021",
        "event_name": "North-South Expressway Phase 1",
        "event_name_vi": "Cao tốc Bắc-Nam phía Đông Giai đoạn 1 hoàn thành",
        "event_type": "growth",
        "start_date": "2021-01-01",
        "end_date": "2025-12-31",
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": -0.2,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["37", "38", "40", "42", "44", "45", "46", "49", "52", "54", "56", "60"],
        "affected_sectors": ["Giao thông", "Logistics", "Bất động sản", "Du lịch"],
        "scope": "national",
        "description_vi": "Các đoạn cao tốc Bắc-Nam phía Đông lần lượt thông tuyến (Mai Sơn-QL45, Nghi Sơn-Diễn Châu, Cam Lộ-La Sơn...), rút ngắn thời gian di chuyển Bắc-Nam từ 50+ xuống còn 20-25 giờ, giảm chi phí logistics toàn quốc.",
        "source": "Ministry of Transport/VEC"
    },
    {
        "event_key": "long_thanh_airport_groundbreaking",
        "event_name": "Long Thanh International Airport Groundbreaking",
        "event_name_vi": "Khởi công Sân bay Quốc tế Long Thành",
        "event_type": "growth",
        "start_date": "2021-01-05",
        "end_date": "2026-12-31",
        "duration_months": 72,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 4.0,
        "affected_provinces": ["75"],
        "affected_sectors": ["Hàng không", "Bất động sản", "Logistics", "FDI"],
        "scope": "national",
        "description_vi": "Sân bay quốc tế Long Thành (Đồng Nai) - dự án 16 tỷ USD, công suất 100 triệu hành khách/năm khi hoàn thành. Giai đoạn 1 (25 triệu HK, dự kiến 2026) là kỳ vọng lớn nhất để giảm tải Tân Sơn Nhất và phát triển vùng Đông Nam Bộ.",
        "source": "Airports Corporation of Vietnam/Ministry of Transport"
    },
    {
        "event_key": "lach_huyen_deepseaport_hai_phong",
        "event_name": "Lach Huyen Deep Sea Port Hai Phong",
        "event_name_vi": "Cảng nước sâu Lạch Huyện - Hải Phòng",
        "event_type": "growth",
        "start_date": "2018-05-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.6,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": -0.1,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["31"],
        "affected_sectors": ["Cảng biển", "Logistics", "Xuất nhập khẩu"],
        "scope": "regional",
        "description_vi": "Cảng nước sâu Lạch Huyện (ODA Nhật Bản, vốn hơn 12.000 tỷ đồng) cho phép tàu container cỡ lớn 100.000 DWT vào trực tiếp, giúp Hải Phòng cạnh tranh với cảng Cái Mép về xuất khẩu quốc tế.",
        "source": "Ministry of Transport/JICA"
    },
    {
        "event_key": "cai_mep_thi_vai_port_2011",
        "event_name": "Cai Mep - Thi Vai Deep Sea Port Complex",
        "event_name_vi": "Cụm Cảng nước sâu Cái Mép - Thị Vải",
        "event_type": "growth",
        "start_date": "2011-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": -0.2,
        "impact_fdi_pct": 4.0,
        "affected_provinces": ["77"],
        "affected_sectors": ["Cảng biển", "Logistics", "Khu công nghiệp"],
        "scope": "national",
        "description_vi": "Cụm cảng Cái Mép-Thị Vải (Bà Rịa-Vũng Tàu) đón tàu mẹ trực tiếp đến Mỹ, châu Âu từ 2011 (không cần trung chuyển qua Singapore). Đây là cảng nước sâu chiến lược duy nhất tại miền Nam Việt Nam.",
        "source": "Vietnam Seaports Association/Ministry of Transport"
    },
]

# ============================================================
# G. NĂNG LƯỢNG & TÀI NGUYÊN (còn thiếu)
# ============================================================
energy_events = [
    {
        "event_key": "solar_fit_boom_2019",
        "event_name": "Solar Power FIT Boom 2019",
        "event_name_vi": "Bùng nổ năng lượng mặt trời FIT 2019",
        "event_type": "growth",
        "start_date": "2017-04-11",
        "end_date": "2021-12-31",
        "duration_months": 56,
        "severity": "extreme",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["58", "60", "72", "45", "64", "84"],
        "affected_sectors": ["Năng lượng tái tạo", "Xây dựng", "Tài chính", "FDI"],
        "scope": "regional",
        "description_vi": "Chính sách giá FIT 9.35 cent/kWh (2017-2019) tạo cơn sốt điện mặt trời: công suất tăng từ 86 MW (2018) lên 16.500 MW chỉ trong 2 năm. Ninh Thuận, Bình Thuận, Tây Ninh bùng nổ đầu tư, song lưới điện quá tải buộc phải cắt giảm phát điện.",
        "source": "Ministry of Industry and Trade/EVN"
    },
    {
        "event_key": "offshore_wind_boom_2021",
        "event_name": "Offshore Wind Power Development",
        "event_name_vi": "Điện gió ngoài khơi - Làn sóng đầu tư mới",
        "event_type": "growth",
        "start_date": "2021-10-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.2,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 8.0,
        "affected_provinces": ["58", "60", "95", "84", "96"],
        "affected_sectors": ["Năng lượng tái tạo", "Cơ sở hạ tầng biển", "FDI"],
        "scope": "national",
        "description_vi": "Việt Nam thu hút hàng chục tỷ USD cam kết đầu tư điện gió ngoài khơi từ Equinor, Orsted, Copenhagen Infrastructure Partners, Macquarie. Tiềm năng 600 GW là một trong các thị trường gió ngoài khơi lớn nhất châu Á.",
        "source": "Ministry of Industry and Trade/World Bank"
    },
    {
        "event_key": "jetp_green_transition_2022",
        "event_name": "Vietnam JETP Just Energy Transition Partnership",
        "event_name_vi": "Đối tác Chuyển đổi Năng lượng Công bằng JETP",
        "event_type": "policy",
        "start_date": "2022-11-14",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": 6.0,
        "affected_provinces": ["58", "60", "72", "77"],
        "affected_sectors": ["Năng lượng tái tạo", "Than đá", "Tài chính xanh"],
        "scope": "national",
        "description_vi": "G7+các đối tác cam kết hỗ trợ Việt Nam 15.5 tỷ USD trong 5 năm để chuyển đổi từ điện than sang tái tạo, với mục tiêu đạt phát thải ròng bằng 0 vào 2050. Cam kết không xây thêm nhà máy nhiệt điện than mới.",
        "source": "JETP Partnership/Ministry of Natural Resources"
    },
    {
        "event_key": "oil_peak_production_1990s",
        "event_name": "Vietnam Oil Production Peak & Bach Ho Field",
        "event_name_vi": "Khai thác dầu khí mỏ Bạch Hổ đỉnh cao",
        "event_type": "growth",
        "start_date": "1986-06-26",
        "end_date": "2005-12-31",
        "duration_months": 234,
        "severity": "extreme",
        "impact_gdp_pct": 3.0,
        "impact_tax_revenue_pct": 15.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["77"],
        "affected_sectors": ["Dầu khí", "Ngân sách Nhà nước", "Năng lượng"],
        "scope": "national",
        "description_vi": "Giàn khoan đầu tiên tại mỏ Bạch Hổ (Vũng Tàu) cho dòng dầu thương mại 1986. Đỉnh sản lượng 400.000 thùng/ngày (năm 2004). Dầu thô chiếm 25-30% thu ngân sách trong suốt thập niên 1990s - 2000s, là trụ cột tài khóa quốc gia.",
        "source": "PetroVietnam/Ministry of Finance"
    },
    {
        "event_key": "coal_industry_quang_ninh",
        "event_name": "Quang Ninh Coal Industry Decline 2010s",
        "event_name_vi": "Ngành Than Quảng Ninh - Giai đoạn suy giảm",
        "event_type": "financial_crisis",
        "start_date": "2013-01-01",
        "end_date": "2020-12-31",
        "duration_months": 96,
        "severity": "medium",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -2.0,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": -0.5,
        "affected_provinces": ["22"],
        "affected_sectors": ["Khai khoáng", "Than đá", "Xuất khẩu khoáng sản"],
        "scope": "regional",
        "description_vi": "Sản lượng khai thác than giảm, tồn kho tích tụ, giá than thế giới sụt giảm. Vinacomin phải cắt giảm nhân sự, GRDP Quảng Ninh bị ảnh hưởng nhưng bù đắp bằng du lịch và bất động sản.",
        "source": "Vinacomin/GSO"
    },
]

# ============================================================
# H. NÔNG NGHIỆP - HÀNG HÓA CÒN THIẾU
# ============================================================
agriculture_events = [
    {
        "event_key": "coffee_price_collapse_2000s",
        "event_name": "Global Coffee Price Collapse 2001-2004",
        "event_name_vi": "Giá cà phê sụp đổ toàn cầu 2001-2004",
        "event_type": "financial_crisis",
        "start_date": "2001-01-01",
        "end_date": "2004-12-31",
        "duration_months": 48,
        "severity": "high",
        "impact_gdp_pct": -0.4,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 1.0,
        "impact_cpi_pct": -0.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["66", "67", "68", "64", "62"],
        "affected_sectors": ["Nông nghiệp", "Xuất khẩu", "Chế biến nông sản"],
        "scope": "regional",
        "description_vi": "Giá cà phê Robusta sụp đổ từ 2000 USD/tấn xuống chỉ còn 450 USD/tấn (2002) - thấp nhất trong 30 năm. Hàng trăm ngàn nông dân Tây Nguyên phá sản, cây cà phê bị chặt bỏ hàng loạt. Đây là cuộc khủng hoảng nông nghiệp tồi tệ nhất vùng Tây Nguyên.",
        "source": "ICO/MARD/GSO"
    },
    {
        "event_key": "rubber_price_collapse_2011_2016",
        "event_name": "Natural Rubber Price Collapse",
        "event_name_vi": "Giá cao su thiên nhiên sụp đổ 2011-2016",
        "event_type": "financial_crisis",
        "start_date": "2011-03-01",
        "end_date": "2016-12-31",
        "duration_months": 69,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.8,
        "impact_cpi_pct": -0.3,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["70", "64", "62", "66"],
        "affected_sectors": ["Nông nghiệp", "Cao su", "Xuất khẩu"],
        "scope": "regional",
        "description_vi": "Giá cao su thiên nhiên giảm từ 6.500 USD/tấn xuống còn 1.200 USD/tấn, tàn phá ngành cao su Bình Phước, Gia Lai, Kon Tum. Tập đoàn Cao su VN lỗ hàng nghìn tỷ, hàng trăm nghìn ha cao su ngừng khai thác.",
        "source": "VRA/Rubber Association"
    },
    {
        "event_key": "black_pepper_price_collapse_2018",
        "event_name": "Black Pepper Price Collapse",
        "event_name_vi": "Giá tiêu đen sụp đổ 2018-2020",
        "event_type": "financial_crisis",
        "start_date": "2017-01-01",
        "end_date": "2020-12-31",
        "duration_months": 48,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.4,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": -0.2,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["70", "67", "64"],
        "affected_sectors": ["Nông nghiệp", "Gia vị", "Xuất khẩu"],
        "scope": "regional",
        "description_vi": "Giá tiêu giảm từ 250.000 VNĐ/kg (2015) xuống còn 40.000 VNĐ/kg (2019) do nguồn cung toàn cầu tăng mạnh. Hàng nghìn hộ trồng tiêu tại Bình Phước, Đắk Nông, Gia Lai phá sản, gánh nặng nợ ngân hàng.",
        "source": "VPA/MARD"
    },
    {
        "event_key": "durian_export_china_boom_2022",
        "event_name": "Durian Export to China Boom",
        "event_name_vi": "Bùng nổ xuất khẩu Sầu riêng sang Trung Quốc",
        "event_type": "growth",
        "start_date": "2022-09-01",
        "end_date": None,
        "duration_months": 36,
        "severity": "high",
        "impact_gdp_pct": 0.4,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 0.5,
        "affected_provinces": ["68", "75", "66", "64"],
        "affected_sectors": ["Nông nghiệp", "Xuất khẩu", "Chế biến nông sản"],
        "scope": "regional",
        "description_vi": "Hiệp định chính thức xuất khẩu sầu riêng tươi sang Trung Quốc (9/2022) tạo cơn sốt: xuất khẩu đạt 2.1 tỷ USD (2023). Nông dân Lâm Đồng, Đắk Lắk, Tiền Giang phá vỡ quy hoạch trồng ào ạt. Tiền Giang và Lâm Đồng là hai tỉnh hưởng lợi nhất.",
        "source": "MARD/VASEP/Customs"
    },
    {
        "event_key": "cashew_boom_export",
        "event_name": "Vietnam Becomes World's Top Cashew Exporter",
        "event_name_vi": "Việt Nam trở thành nước XK hạt điều số 1 thế giới",
        "event_type": "growth",
        "start_date": "2005-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.8,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 0.3,
        "affected_provinces": ["70", "75", "77", "93"],
        "affected_sectors": ["Nông nghiệp", "Chế biến nông sản", "Xuất khẩu"],
        "scope": "regional",
        "description_vi": "Việt Nam trở thành quốc gia xuất khẩu hạt điều lớn nhất thế giới từ 2006, chiếm 50%+ thị phần toàn cầu, dù phải nhập nguyên liệu từ châu Phi. Bình Phước là trung tâm chế biến hạt điều của cả nước.",
        "source": "VINACAS/MARD"
    },
    {
        "event_key": "rice_export_ban_india_2023",
        "event_name": "India Rice Export Ban - Vietnam Benefits",
        "event_name_vi": "Ấn Độ cấm xuất khẩu gạo - Gạo Việt lên đỉnh",
        "event_type": "growth",
        "start_date": "2023-07-20",
        "end_date": "2024-12-31",
        "duration_months": 18,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.6,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": 0.2,
        "affected_provinces": ["91", "89", "80", "82", "92"],
        "affected_sectors": ["Nông nghiệp", "Xuất khẩu gạo", "Chế biến thực phẩm"],
        "scope": "regional",
        "description_vi": "Ấn Độ (chiếm 40% xuất khẩu gạo thế giới) cấm xuất khẩu gạo đẩy giá gạo 5% tấm Việt Nam lên 663 USD/tấn (cao nhất 15 năm). Nông dân ĐBSCL và thương lái xuất khẩu hưởng lợi lớn nhưng gây lạm phát lương thực nội địa.",
        "source": "VFA/MARD/Reuters"
    },
]

# ============================================================
# I. ĐỊA CHÍNH TRỊ TOÀN CẦU ẢNH HƯỞNG TRỰC TIẾP (còn thiếu)
# ============================================================
geopolitics_events = [
    {
        "event_key": "tpp_collapse_2017",
        "event_name": "TPP Collapse - US Withdrawal",
        "event_name_vi": "Hiệp định TPP sụp đổ - Mỹ rút khỏi",
        "event_type": "trade_war",
        "start_date": "2017-01-23",
        "end_date": "2019-01-14",
        "duration_months": 24,
        "severity": "high",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.0,
        "impact_fdi_pct": -5.0,
        "affected_provinces": ["79", "74", "75", "36", "40"],
        "affected_sectors": ["Dệt may", "Da giày", "Thủy sản", "FDI"],
        "scope": "national",
        "description_vi": "Trump ký lệnh rút khỏi TPP ngay ngày đầu nhậm chức. Việt Nam là nước thiệt hại nhất (dự kiến hưởng lợi 25 tỷ USD/năm từ TPP). Dệt may, da giày mất lợi thế thuế quan 0% vào thị trường Mỹ. Sau đó CPTPP (không có Mỹ) thay thế.",
        "source": "USTR/MOIT"
    },
    {
        "event_key": "south_china_sea_hd981_2014",
        "event_name": "South China Sea HD-981 Oil Rig Crisis",
        "event_name_vi": "Khủng hoảng giàn khoan HD-981 Biển Đông",
        "event_type": "geopolitics",
        "start_date": "2014-05-02",
        "end_date": "2014-07-15",
        "duration_months": 3,
        "severity": "high",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": -10.0,
        "affected_provinces": ["75", "74", "79", "42"],
        "affected_sectors": ["FDI", "Du lịch", "Thương mại"],
        "scope": "national",
        "description_vi": "Trung Quốc đặt giàn khoan HD-981 vào vùng đặc quyền kinh tế Việt Nam gây cuộc biểu tình bài Trung Quốc 13-15/5/2014. Hàng trăm nhà máy FDI bị tấn công tại Bình Dương, Đồng Nai, Hà Tĩnh gây thiệt hại hàng nghìn tỷ đồng.",
        "source": "Ministry of Foreign Affairs/Government"
    },
    {
        "event_key": "myanmar_coup_supply_chain_2021",
        "event_name": "Myanmar Coup - Vietnam FDI Diversion",
        "event_name_vi": "Đảo chính Myanmar - Dòng vốn FDI chuyển sang Việt Nam",
        "event_type": "geopolitics",
        "start_date": "2021-02-01",
        "end_date": "2023-12-31",
        "duration_months": 35,
        "severity": "medium",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 4.0,
        "affected_provinces": ["40", "24", "27", "31"],
        "affected_sectors": ["Dệt may", "Da giày", "FDI", "Khu công nghiệp"],
        "scope": "national",
        "description_vi": "Đảo chính Myanmar khiến các nhà đầu tư dệt may, da giày đang cân nhắc Myanmar chuyển hướng sang Việt Nam. Đặc biệt ngành dệt may Việt Nam hưởng lợi từ dòng đơn hàng chuyển dịch.",
        "source": "MPI/VITAS"
    },
    {
        "event_key": "covid_zero_china_border_2020_2022",
        "event_name": "China Zero-COVID Border Disruption",
        "event_name_vi": "Zero-COVID Trung Quốc - Gián đoạn thương mại biên mậu",
        "event_type": "geopolitics",
        "start_date": "2020-02-01",
        "end_date": "2023-01-08",
        "duration_months": 36,
        "severity": "high",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 0.8,
        "impact_fdi_pct": -3.0,
        "affected_provinces": ["20", "10", "04", "22"],
        "affected_sectors": ["Xuất nhập khẩu", "Nông sản", "Logistics biên mậu"],
        "scope": "regional",
        "description_vi": "Chính sách Zero-COVID của Trung Quốc (2020-2022) gây ùn tắc hàng nghìn container tại Lạng Sơn, Lào Cai, Cao Bằng, Quảng Ninh. Nông sản tươi (thanh long, dưa hấu, mít...) hàng trăm nghìn tấn bị ủ thối tại cửa khẩu.",
        "source": "Customs Department/Ministry of Agriculture"
    },
]

# ============================================================
# J. CÁC TỈNH CỤ THỂ VẪN CÒN THIẾU SỰ KIỆN ĐẶC THÙNG
# ============================================================
province_specific_events = [
    # Quang Binh - Phong Nha tourism boom
    {
        "event_key": "phong_nha_tourism_boom_2009",
        "event_name": "Phong Nha Son Doong Cave Tourism Boom",
        "event_name_vi": "Bùng nổ du lịch hang Sơn Đoòng - Quảng Bình",
        "event_type": "growth",
        "start_date": "2013-01-01",
        "end_date": "2019-12-31",
        "duration_months": 84,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.6,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["44"],
        "affected_sectors": ["Du lịch", "Dịch vụ", "Bất động sản"],
        "scope": "regional",
        "description_vi": "Hang Sơn Đoòng (hang động tự nhiên lớn nhất thế giới, phát hiện 2009) mở cửa đón khách quốc tế từ 2013 do Oxalis. Cùng với Phong Nha-Kẻ Bàng UNESCO, biến Quảng Bình từ tỉnh thuần nông thành điểm du lịch hot nhất Bắc miền Trung.",
        "source": "Quang Binh Portal/UNESCO"
    },
    # Khanh Hoa - Nha Trang tourism
    {
        "event_key": "nha_trang_russian_tourism_boom",
        "event_name": "Nha Trang Russian & Chinese Tourism Boom",
        "event_name_vi": "Nha Trang bùng nổ du lịch Nga và Trung Quốc",
        "event_type": "growth",
        "start_date": "2010-01-01",
        "end_date": "2019-12-31",
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["56"],
        "affected_sectors": ["Du lịch", "Bất động sản", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "Du khách Nga (2010-2013) và sau đó là du khách Trung Quốc (2015-2019) đổ về Nha Trang theo đường charter. Khách TQ tăng từ 400.000 lên 4 triệu lượt/năm. Bất động sản nghỉ dưỡng và condo-hotel bùng nổ, nhưng tạo ra bong bóng và vấn đề quản lý.",
        "source": "Khanh Hoa Portal/Vietnam Tourism"
    },
    # Da Nang technology city
    {
        "event_key": "danang_tech_city_2010",
        "event_name": "Da Nang High-Tech Park & IT Hub",
        "event_name_vi": "Đà Nẵng - Thành phố Công nghệ thông tin",
        "event_type": "growth",
        "start_date": "2010-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 1.0,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["48"],
        "affected_sectors": ["Công nghệ thông tin", "Du lịch", "Dịch vụ", "FDI"],
        "scope": "regional",
        "description_vi": "Đà Nẵng xây dựng Khu công nghệ cao và hệ sinh thái IT với Trung tâm Phần mềm DN, thu hút FPT Software, Harvey Nash, TMA Solutions. Song song đó du lịch bùng nổ với Bà Nà Hills, Non Nước biến Đà Nẵng thành đô thị đáng sống hàng đầu VN.",
        "source": "Da Nang Portal/MPI"
    },
    # Can Tho - ASEAN logistics hub
    {
        "event_key": "can_tho_regional_hub_2010s",
        "event_name": "Can Tho Mekong Regional Hub Development",
        "event_name_vi": "Cần Thơ - Trung tâm vùng ĐBSCL",
        "event_type": "growth",
        "start_date": "2010-01-01",
        "end_date": "2020-12-31",
        "duration_months": 132,
        "severity": "medium",
        "impact_gdp_pct": 0.6,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["92"],
        "affected_sectors": ["Dịch vụ", "Logistics", "Nông nghiệp công nghệ cao", "Y tế"],
        "scope": "regional",
        "description_vi": "Cần Thơ phát triển thành đô thị loại I của ĐBSCL với sân bay quốc tế, bệnh viện hạng I, đại học tầm cỡ. Trung tâm xuất khẩu thủy sản, gạo, trái cây vùng. Cầu Cần Thơ (2010) và hệ thống logistics đường thủy thúc đẩy tăng trưởng.",
        "source": "Can Tho Portal/GSO"
    },
    # Dak Lak - Buon Ma Thuot coffee capital
    {
        "event_key": "buon_ma_thuot_coffee_capital",
        "event_name": "Buon Ma Thuot World Coffee Capital",
        "event_name_vi": "Buôn Ma Thuột - Thủ đô Cà phê Thế giới",
        "event_type": "growth",
        "start_date": "2010-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "medium",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 1.0,
        "affected_provinces": ["66"],
        "affected_sectors": ["Nông nghiệp", "Du lịch", "Chế biến nông sản", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "Đắk Lắk chiếm 30-35% sản lượng cà phê Việt Nam, Buôn Ma Thuột nổi tiếng là 'Thủ đô cà phê thế giới' và là nơi tổ chức Festival Cà phê quốc tế. Nestlé, Trung Nguyên, Simexco đặt nhà máy chế biến quy mô lớn.",
        "source": "Dak Lak Portal/MARD"
    },
    # Ba Ria Vung Tau - petrochemical hub
    {
        "event_key": "vung_tau_oil_petroleum_hub",
        "event_name": "Vung Tau Petroleum & SEZ Development",
        "event_name_vi": "Vũng Tàu - Trung tâm Dầu khí & Đặc khu Kinh tế",
        "event_type": "growth",
        "start_date": "1990-01-01",
        "end_date": "2010-12-31",
        "duration_months": 252,
        "severity": "extreme",
        "impact_gdp_pct": 4.0,
        "impact_tax_revenue_pct": 20.0,
        "impact_unemployment_pct": -1.5,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 10.0,
        "affected_provinces": ["77"],
        "affected_sectors": ["Dầu khí", "Hóa dầu", "Dịch vụ dầu khí", "Du lịch"],
        "scope": "regional",
        "description_vi": "Bà Rịa-Vũng Tàu là tỉnh có GDP cao nhất Việt Nam trong nhiều năm thập niên 1990-2000s nhờ dầu khí mỏ Bạch Hổ. Cụm Cái Mép, lọc hóa dầu Long Sơn, cảng nước sâu tạo nên nền công nghiệp đa dạng nhất miền Nam.",
        "source": "PetroVietnam/Ba Ria Vung Tau Portal"
    },
    # Quang Ngai - Hoa Phat steel
    {
        "event_key": "hoa_phat_dung_quat_steel_2020",
        "event_name": "Hoa Phat Dung Quat Steel Phase 1-2",
        "event_name_vi": "Khu liên hợp thép Hòa Phát Dung Quất I & II",
        "event_type": "growth",
        "start_date": "2020-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "extreme",
        "impact_gdp_pct": 3.0,
        "impact_tax_revenue_pct": 8.0,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 1.0,
        "affected_provinces": ["51"],
        "affected_sectors": ["Thép", "Công nghiệp nặng", "Cảng biển"],
        "scope": "regional",
        "description_vi": "Tổ hợp thép Hòa Phát Dung Quất I (4 triệu tấn/năm, hoạt động từ 2020) và giai đoạn II (4 triệu tấn, đầu tư 85.000 tỷ đồng) biến Quảng Ngãi thành trung tâm thép lớn nhất Đông Nam Á. Đóng góp hàng chục nghìn tỷ vào GRDP tỉnh.",
        "source": "Hoa Phat Group/Quang Ngai Portal"
    },
    # Hai Duong - automotive & ceramic cluster
    {
        "event_key": "hai_duong_industrial_cluster",
        "event_name": "Hai Duong Ceramic & Automotive Cluster",
        "event_name_vi": "Cụm công nghiệp Gốm sứ - Ô tô Hải Dương",
        "event_type": "growth",
        "start_date": "2005-01-01",
        "end_date": "2020-12-31",
        "duration_months": 180,
        "severity": "medium",
        "impact_gdp_pct": 0.7,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["30"],
        "affected_sectors": ["Gốm sứ", "Sản xuất ô tô", "Cơ khí"],
        "scope": "regional",
        "description_vi": "Hải Dương nổi tiếng với làng gốm sứ Chu Đậu và cụm công nghiệp ô tô (Isuzu, Ford). Nằm giữa tam giác Hà Nội-Hải Phòng-Quảng Ninh, thu hút nhiều FDI đa ngành.",
        "source": "Hai Duong Portal"
    },
    # Nghe An - Vingroup industrial complex
    {
        "event_key": "vsip_nghe_an_2022",
        "event_name": "VSIP Nghe An Industrial Park",
        "event_name_vi": "Khu công nghiệp VSIP Nghệ An - Bắc miền Trung bứt phá",
        "event_type": "growth",
        "start_date": "2022-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 3.0,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 6.0,
        "affected_provinces": ["40"],
        "affected_sectors": ["Khu công nghiệp", "Sản xuất điện tử", "FDI"],
        "scope": "regional",
        "description_vi": "VSIP Nghệ An thu hút Luxshare, Goertek, Sunny Opotech (Apple supply chain). Cùng với hạ tầng KKT Đông Nam Nghệ An, Nghệ An bứt phá thu hút FDI bắc-nam miền Trung, giảm bớt bất bình đẳng vùng.",
        "source": "Nghe An Portal/VSIP"
    },
    # Tra Vinh - wind power & LNG
    {
        "event_key": "tra_vinh_dong_hai_wind_lng",
        "event_name": "Tra Vinh Offshore Wind & LNG Terminal",
        "event_name_vi": "Điện gió ngoài khơi Đông Hải - LNG Trà Vinh",
        "event_type": "growth",
        "start_date": "2022-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.2,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["84"],
        "affected_sectors": ["Năng lượng tái tạo", "Điện gió", "LNG"],
        "scope": "regional",
        "description_vi": "Dự án điện gió Đông Hải 1 (100 MW, 100 triệu USD) tại Trà Vinh là điện gió offshore đầu tiên Việt Nam vào lưới. Cùng cảng LNG Thị Vải và hướng phát triển năng lượng biển, Trà Vinh trở thành trung tâm năng lượng mới của ĐBSCL.",
        "source": "Tra Vinh Portal/Ministry of Industry and Trade"
    },
]

# ============================================================
# K. CÁC SỰ KIỆN VĨ MÔ TOÀN CẦU ẢNH HƯỞNG VIỆT NAM
# ============================================================
global_macro_events = [
    {
        "event_key": "dot_com_bust_2001",
        "event_name": "Dot-com Bust & 9/11 Shock",
        "event_name_vi": "Bong bóng dot-com vỡ & Sự kiện 11/9",
        "event_type": "financial_crisis",
        "start_date": "2001-01-01",
        "end_date": "2003-12-31",
        "duration_months": 36,
        "severity": "medium",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": -8.0,
        "affected_provinces": [],
        "affected_sectors": ["FDI", "Du lịch", "Xuất nhập khẩu"],
        "scope": "global",
        "description_vi": "Bong bóng dot-com vỡ (2000-2001) và cuộc tấn công khủng bố 11/9/2001 gây sụt giảm FDI toàn cầu, du lịch Việt Nam bị ảnh hưởng dù Việt Nam ổn định hơn nhiều so với các nước trong khu vực.",
        "source": "World Bank/IMF"
    },
    {
        "event_key": "global_commodity_supercycle_2004_2008",
        "event_name": "Global Commodity Supercycle",
        "event_name_vi": "Siêu chu kỳ hàng hóa toàn cầu 2004-2008",
        "event_type": "growth",
        "start_date": "2004-01-01",
        "end_date": "2008-06-30",
        "duration_months": 54,
        "severity": "high",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 5.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 3.0,
        "impact_fdi_pct": 8.0,
        "affected_provinces": ["77", "51", "66", "64"],
        "affected_sectors": ["Dầu khí", "Khai khoáng", "Nông nghiệp", "Năng lượng"],
        "scope": "global",
        "description_vi": "Cầu nguyên liệu thô từ Trung Quốc đẩy giá dầu lên 147 USD/thùng, giá cao su, than, cà phê, gạo tăng mạnh. Việt Nam hưởng lợi từ xuất khẩu dầu thô, gạo, cà phê nhưng chịu áp lực nhập khẩu lạm phát.",
        "source": "World Bank/IMF"
    },
    {
        "event_key": "fed_taper_tantrum_2013",
        "event_name": "Fed Taper Tantrum - Capital Flight",
        "event_name_vi": "Taper Tantrum Mỹ - Vốn tháo chạy thị trường mới nổi",
        "event_type": "financial_crisis",
        "start_date": "2013-05-22",
        "end_date": "2014-03-31",
        "duration_months": 10,
        "severity": "medium",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": -3.0,
        "affected_provinces": [],
        "affected_sectors": ["Tài chính ngân hàng", "Chứng khoán", "BĐS"],
        "scope": "global",
        "description_vi": "FED tuyên bố giảm mua trái phiếu gây vốn tháo chạy khỏi thị trường mới nổi. VND chịu áp lực mất giá, VN-Index sụt giảm, dù Việt Nam ít tổn thương hơn nhờ kiểm soát vốn.",
        "source": "State Bank of Vietnam/World Bank"
    },
    {
        "event_key": "china_economic_slowdown_2015",
        "event_name": "China Economic Slowdown & CNY Devaluation",
        "event_name_vi": "Kinh tế Trung Quốc tăng trưởng chậm lại - Phá giá NDT",
        "event_type": "financial_crisis",
        "start_date": "2015-01-01",
        "end_date": "2016-12-31",
        "duration_months": 24,
        "severity": "medium",
        "impact_gdp_pct": -0.4,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": -0.5,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["89", "91", "20", "10"],
        "affected_sectors": ["Xuất nhập khẩu", "Nông sản", "FDI Trung Quốc"],
        "scope": "global",
        "description_vi": "Trung Quốc phá giá NDT và tăng trưởng chậm lại làm giảm nhu cầu nhập khẩu nông sản từ Việt Nam, cạnh tranh xuất khẩu tăng. Gây sức ép lên SBV phải điều chỉnh tỷ giá.",
        "source": "World Bank/ADB"
    },
    {
        "event_key": "global_supply_chain_disruption_2021",
        "event_name": "Global Supply Chain Disruption 2021",
        "event_name_vi": "Khủng hoảng chuỗi cung ứng toàn cầu 2021-2022",
        "event_type": "geopolitics",
        "start_date": "2021-01-01",
        "end_date": "2022-12-31",
        "duration_months": 24,
        "severity": "high",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 3.0,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["79", "74", "75", "31"],
        "affected_sectors": ["Xuất nhập khẩu", "Logistics", "Sản xuất", "Điện tử"],
        "scope": "global",
        "description_vi": "Tắc nghẽn cảng toàn cầu, thiếu chip bán dẫn, thiếu container... làm giá cước vận tải tăng 400-500%. Sản xuất VN bị gián đoạn nguyên liệu đầu vào, đặc biệt linh kiện điện tử và nguyên liệu dệt may.",
        "source": "World Bank/Vietnam Logistics Association"
    },
]

# ============================================================
# TỔNG HỢP & CHẠY
# ============================================================
all_new_events = (
    policy_events +
    financial_events +
    trade_events +
    disaster_events +
    fdi_events +
    infrastructure_events +
    energy_events +
    agriculture_events +
    geopolitics_events +
    province_specific_events +
    global_macro_events
)

def run():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        existing_events = json.load(f)

    existing_keys = {e["event_key"] for e in existing_events}

    added = []
    skipped = []
    for e in all_new_events:
        if e["event_key"] not in existing_keys:
            existing_events.append(e)
            existing_keys.add(e["event_key"])
            added.append(e["event_key"])
        else:
            skipped.append(e["event_key"])

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(existing_events, f, ensure_ascii=False, indent=2)

    print(f"\\n✅ Thêm mới: {len(added)} sự kiện")
    print(f"⏭️  Đã tồn tại (bỏ qua): {len(skipped)} sự kiện")
    print(f"📊 Tổng số sự kiện trong DB: {len(existing_events)}")
    print(f"\\n📋 Breakdown theo nhóm:")
    print(f"   A. Chính sách & Thể chế: {len(policy_events)} events")
    print(f"   B. Tài chính & Thị trường: {len(financial_events)} events")
    print(f"   C. Hiệp định thương mại: {len(trade_events)} events")
    print(f"   D. Thiên tai bổ sung: {len(disaster_events)} events")
    print(f"   E. FDI theo tỉnh: {len(fdi_events)} events")
    print(f"   F. Hạ tầng chiến lược: {len(infrastructure_events)} events")
    print(f"   G. Năng lượng & Tài nguyên: {len(energy_events)} events")
    print(f"   H. Nông nghiệp & Hàng hóa: {len(agriculture_events)} events")
    print(f"   I. Địa chính trị: {len(geopolitics_events)} events")
    print(f"   J. Tỉnh thành đặc thù: {len(province_specific_events)} events")
    print(f"   K. Vĩ mô toàn cầu: {len(global_macro_events)} events")
    print(f"\\n🔗 Tổng mới đề xuất: {len(all_new_events)} events")

if __name__ == "__main__":
    run()
