import json
import random
import os
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "data"
os.makedirs(DATA_DIR, exist_ok=True)

# 1. Generate 63 Provinces
provinces = [
    ("01", "Hà Nội", "Đồng bằng sông Hồng", 21.0285, 105.8542, 1180000, 8435700, 165000, 295000, 6.2, 2.1, ["Dịch vụ", "Công nghệ thông tin", "Sản xuất"], 0.88, "low"),
    ("02", "Hà Giang", "Trung du và miền núi phía Bắc", 22.8233, 104.9839, 28000, 854679, 2500, 2100, 0.1, 1.8, ["Nông nghiệp", "Du lịch"], 0.78, "medium"),
    ("04", "Cao Bằng", "Trung du và miền núi phía Bắc", 22.6667, 106.2500, 20000, 530341, 1800, 1500, 0.05, 2.0, ["Nông nghiệp", "Khai khoáng"], 0.75, "medium"),
    ("06", "Bắc Kạn", "Trung du và miền núi phía Bắc", 22.1470, 105.8348, 15000, 313905, 1200, 800, 0.02, 2.2, ["Nông nghiệp", "Lâm nghiệp"], 0.76, "medium"),
    ("08", "Tuyên Quang", "Trung du và miền núi phía Bắc", 21.8213, 105.2155, 38000, 784811, 3100, 2800, 0.2, 1.9, ["Nông nghiệp", "Sản xuất"], 0.80, "medium"),
    ("10", "Lào Cai", "Trung du và miền núi phía Bắc", 22.4856, 103.9707, 65000, 730420, 4500, 5000, 0.5, 1.8, ["Du lịch", "Thương mại", "Khai khoáng"], 0.82, "medium"),
    ("11", "Điện Biên", "Trung du và miền núi phía Bắc", 21.3860, 103.0152, 22000, 598856, 2100, 1600, 0.08, 2.4, ["Nông nghiệp", "Du lịch"], 0.76, "high"),
    ("12", "Lai Châu", "Trung du và miền núi phía Bắc", 22.3951, 103.4560, 18000, 460196, 1500, 1200, 0.05, 2.1, ["Nông nghiệp"], 0.75, "high"),
    ("14", "Sơn La", "Trung du và miền núi phía Bắc", 21.3283, 103.9146, 52000, 1248415, 3800, 4100, 0.3, 1.7, ["Nông nghiệp", "Sản xuất"], 0.79, "medium"),
    ("15", "Yên Bái", "Trung du và miền núi phía Bắc", 21.7163, 104.9009, 39000, 821030, 3200, 2900, 0.25, 2.0, ["Nông nghiệp", "Sản xuất"], 0.80, "medium"),
    ("17", "Hoà Bình", "Trung du và miền núi phía Bắc", 20.8133, 105.3384, 55000, 854131, 4000, 4500, 0.4, 2.1, ["Sản xuất", "Du lịch", "Nông nghiệp"], 0.81, "medium"),
    ("19", "Thái Nguyên", "Trung du và miền núi phía Bắc", 21.5942, 105.8482, 150000, 1286751, 8500, 18000, 1.5, 1.9, ["Sản xuất", "Công nghệ cao", "Khai khoáng"], 0.85, "low"),
    ("20", "Lạng Sơn", "Trung du và miền núi phía Bắc", 21.8530, 106.7580, 45000, 781655, 3500, 5500, 0.3, 2.3, ["Thương mại", "Nông nghiệp"], 0.80, "medium"),
    ("22", "Quảng Ninh", "Đồng bằng sông Hồng", 21.0065, 107.2917, 280000, 1320324, 18000, 38000, 2.5, 1.8, ["Du lịch", "Khai khoáng", "Dịch vụ"], 0.87, "low"),
    ("24", "Bắc Giang", "Trung du và miền núi phía Bắc", 21.2731, 106.1946, 160000, 1803950, 12000, 14000, 1.8, 1.7, ["Sản xuất", "Nông nghiệp"], 0.84, "low"),
    ("25", "Phú Thọ", "Trung du và miền núi phía Bắc", 21.3259, 105.2155, 88000, 1463726, 7500, 8500, 0.8, 1.9, ["Sản xuất", "Nông nghiệp"], 0.82, "medium"),
    ("26", "Vĩnh Phúc", "Đồng bằng sông Hồng", 21.3113, 105.5843, 145000, 1151154, 11000, 30000, 1.6, 1.6, ["Sản xuất công nghiệp", "Dịch vụ"], 0.86, "low"),
    ("27", "Bắc Ninh", "Đồng bằng sông Hồng", 21.1861, 106.0763, 240000, 1368840, 16000, 31000, 3.2, 1.5, ["Công nghệ cao", "Sản xuất"], 0.88, "low"),
    ("30", "Hải Dương", "Đồng bằng sông Hồng", 20.9388, 106.3315, 175000, 1892254, 14000, 18000, 1.4, 1.7, ["Sản xuất", "Nông nghiệp"], 0.85, "low"),
    ("31", "Hải Phòng", "Đồng bằng sông Hồng", 20.8449, 106.6881, 380000, 2028514, 25000, 65000, 3.5, 1.6, ["Cảng biển", "Sản xuất", "Dịch vụ"], 0.87, "low"),
    ("33", "Hưng Yên", "Đồng bằng sông Hồng", 20.8519, 106.0505, 125000, 1252731, 10000, 12000, 1.2, 1.8, ["Sản xuất", "Nông nghiệp"], 0.84, "medium"),
    ("34", "Thái Bình", "Đồng bằng sông Hồng", 20.4463, 106.3366, 115000, 1860447, 9500, 11000, 0.9, 1.9, ["Nông nghiệp", "Sản xuất"], 0.83, "medium"),
    ("35", "Hà Nam", "Đồng bằng sông Hồng", 20.5453, 105.9126, 92000, 852800, 6500, 10500, 1.1, 1.7, ["Sản xuất", "Dịch vụ"], 0.84, "medium"),
    ("36", "Nam Định", "Đồng bằng sông Hồng", 20.4357, 106.1770, 95000, 1836269, 8500, 8000, 0.7, 2.0, ["Nông nghiệp", "Dệt may"], 0.82, "medium"),
    ("37", "Ninh Bình", "Đồng bằng sông Hồng", 20.2539, 105.9745, 82000, 982487, 7000, 15000, 0.8, 1.8, ["Du lịch", "Sản xuất"], 0.85, "low"),
    ("38", "Thanh Hóa", "Bắc Trung Bộ và Duyên hải miền Trung", 19.8075, 105.7766, 260000, 3640128, 19000, 35000, 2.1, 2.1, ["Lọc hóa dầu", "Nông nghiệp", "Du lịch"], 0.85, "low"),
    ("40", "Nghệ An", "Bắc Trung Bộ và Duyên hải miền Trung", 18.6796, 105.6813, 185000, 3327791, 14000, 18000, 1.2, 2.2, ["Nông nghiệp", "Sản xuất"], 0.83, "medium"),
    ("42", "Hà Tĩnh", "Bắc Trung Bộ và Duyên hải miền Trung", 18.3428, 105.9056, 95000, 1288866, 7500, 12000, 1.5, 2.3, ["Khai khoáng", "Sản xuất"], 0.82, "medium"),
    ("44", "Quảng Bình", "Bắc Trung Bộ và Duyên hải miền Trung", 17.4833, 106.5997, 52000, 895430, 4500, 6000, 0.3, 2.4, ["Du lịch", "Nông nghiệp"], 0.80, "medium"),
    ("45", "Quảng Trị", "Bắc Trung Bộ và Duyên hải miền Trung", 16.7486, 107.1932, 42000, 632375, 3800, 4500, 0.2, 2.5, ["Nông nghiệp", "Thương mại"], 0.78, "high"),
    ("46", "Thừa Thiên Huế", "Bắc Trung Bộ và Duyên hải miền Trung", 16.4637, 107.5905, 68000, 1128620, 6000, 9500, 0.6, 2.2, ["Du lịch", "Dịch vụ"], 0.83, "medium"),
    ("48", "Đà Nẵng", "Bắc Trung Bộ và Duyên hải miền Trung", 16.0544, 108.2022, 135000, 1134310, 22000, 25000, 2.2, 2.5, ["Du lịch", "Công nghệ thông tin", "Dịch vụ"], 0.86, "low"),
    ("49", "Quảng Nam", "Bắc Trung Bộ và Duyên hải miền Trung", 15.5683, 107.9897, 118000, 1495812, 9500, 18000, 1.3, 2.1, ["Sản xuất ô tô", "Du lịch", "Nông nghiệp"], 0.85, "low"),
    ("51", "Quảng Ngãi", "Bắc Trung Bộ và Duyên hải miền Trung", 15.1205, 108.7923, 125000, 1231697, 8500, 22000, 1.4, 2.0, ["Lọc hóa dầu", "Sản xuất"], 0.84, "medium"),
    ("52", "Bình Định", "Bắc Trung Bộ và Duyên hải miền Trung", 13.7770, 109.2227, 115000, 1486918, 8000, 13000, 0.8, 1.9, ["Du lịch", "Nông nghiệp"], 0.83, "medium"),
    ("54", "Phú Yên", "Bắc Trung Bộ và Duyên hải miền Trung", 13.0886, 109.3076, 52000, 870956, 4500, 5500, 0.4, 2.2, ["Du lịch", "Nông nghiệp"], 0.80, "medium"),
    ("56", "Khánh Hòa", "Bắc Trung Bộ và Duyên hải miền Trung", 12.2388, 109.1967, 118000, 1192500, 11000, 17000, 1.2, 2.1, ["Du lịch", "Dịch vụ", "Thủy sản"], 0.85, "low"),
    ("58", "Ninh Thuận", "Bắc Trung Bộ và Duyên hải miền Trung", 11.5587, 108.9880, 48000, 590467, 3500, 4000, 0.5, 2.4, ["Năng lượng tái tạo", "Nông nghiệp"], 0.79, "high"),
    ("60", "Bình Thuận", "Bắc Trung Bộ và Duyên hải miền Trung", 10.9333, 108.1000, 98000, 1230808, 7500, 10500, 0.9, 1.8, ["Du lịch", "Năng lượng", "Thủy sản"], 0.83, "medium"),
    ("62", "Kon Tum", "Tây Nguyên", 14.3497, 108.0000, 32000, 540438, 2500, 3500, 0.1, 2.3, ["Nông nghiệp", "Lâm nghiệp"], 0.76, "high"),
    ("64", "Gia Lai", "Tây Nguyên", 13.9833, 108.0000, 85000, 1513847, 6500, 5500, 0.4, 2.1, ["Nông nghiệp"], 0.81, "medium"),
    ("66", "Đắk Lắk", "Tây Nguyên", 12.6667, 108.0500, 115000, 1869322, 9500, 8500, 0.6, 2.0, ["Nông nghiệp", "Năng lượng"], 0.82, "medium"),
    ("67", "Đắk Nông", "Tây Nguyên", 12.0000, 107.6917, 45000, 622168, 3200, 4000, 0.3, 2.2, ["Khai khoáng", "Nông nghiệp"], 0.78, "medium"),
    ("68", "Lâm Đồng", "Tây Nguyên", 11.9465, 108.4419, 118000, 1296906, 11000, 12000, 0.5, 1.8, ["Nông nghiệp công nghệ cao", "Du lịch"], 0.84, "medium"),
    ("70", "Bình Phước", "Đông Nam Bộ", 11.7500, 106.9167, 85000, 994679, 7500, 11000, 1.2, 1.6, ["Sản xuất", "Nông nghiệp"], 0.83, "medium"),
    ("72", "Tây Ninh", "Đông Nam Bộ", 11.3101, 106.0967, 105000, 1169165, 8500, 11500, 1.4, 1.5, ["Sản xuất", "Nông nghiệp"], 0.84, "low"),
    ("74", "Bình Dương", "Đông Nam Bộ", 11.1643, 106.6346, 450000, 2426561, 45000, 68000, 5.2, 1.2, ["Sản xuất công nghiệp", "Dịch vụ"], 0.88, "low"),
    ("75", "Đồng Nai", "Đông Nam Bộ", 10.9416, 106.8209, 420000, 3097107, 38000, 58000, 4.5, 1.4, ["Sản xuất công nghiệp", "Dịch vụ"], 0.87, "low"),
    ("77", "Bà Rịa - Vũng Tàu", "Đông Nam Bộ", 10.4938, 107.1708, 380000, 1148313, 18000, 85000, 3.8, 1.5, ["Lọc hóa dầu", "Du lịch", "Cảng biển"], 0.89, "low"),
    ("79", "Hồ Chí Minh", "Đông Nam Bộ", 10.8231, 106.6297, 1550000, 8993082, 350000, 450000, 8.5, 2.5, ["Dịch vụ", "Tài chính", "Sản xuất"], 0.89, "low"),
    ("80", "Long An", "Đồng bằng sông Cửu Long", 10.5333, 106.1667, 168000, 1688547, 14000, 21000, 1.8, 1.6, ["Sản xuất", "Nông nghiệp"], 0.85, "low"),
    ("82", "Tiền Giang", "Đồng bằng sông Cửu Long", 10.3601, 106.3315, 118000, 1764185, 9500, 10500, 0.7, 1.9, ["Nông nghiệp", "Sản xuất"], 0.84, "medium"),
    ("83", "Bến Tre", "Đồng bằng sông Cửu Long", 10.2443, 106.3765, 68000, 1288463, 5500, 6000, 0.4, 2.2, ["Nông nghiệp"], 0.82, "medium"),
    ("84", "Trà Vinh", "Đồng bằng sông Cửu Long", 9.9409, 106.3400, 75000, 1009168, 4800, 6500, 0.6, 2.4, ["Nông nghiệp", "Năng lượng"], 0.81, "medium"),
    ("86", "Vĩnh Long", "Đồng bằng sông Cửu Long", 10.2520, 105.9610, 82000, 1022791, 5800, 7000, 0.5, 2.1, ["Nông nghiệp", "Sản xuất"], 0.82, "medium"),
    ("87", "Đồng Tháp", "Đồng bằng sông Cửu Long", 10.4638, 105.6322, 105000, 1599504, 7500, 8500, 0.6, 1.9, ["Nông nghiệp"], 0.83, "medium"),
    ("89", "An Giang", "Đồng bằng sông Cửu Long", 10.5186, 105.1118, 135000, 1908352, 9500, 9000, 0.5, 2.5, ["Nông nghiệp", "Thương mại"], 0.82, "high"),
    ("91", "Kiên Giang", "Đồng bằng sông Cửu Long", 9.9575, 105.1554, 125000, 1723067, 11000, 13000, 0.8, 1.8, ["Du lịch", "Nông nghiệp"], 0.84, "medium"),
    ("92", "Cần Thơ", "Đồng bằng sông Cửu Long", 10.0451, 105.7469, 135000, 1235171, 16000, 12000, 1.4, 2.3, ["Dịch vụ", "Sản xuất", "Nông nghiệp"], 0.85, "low"),
    ("93", "Hậu Giang", "Đồng bằng sông Cửu Long", 9.7828, 105.5841, 55000, 733017, 3500, 5000, 0.4, 2.1, ["Nông nghiệp"], 0.81, "medium"),
    ("94", "Sóc Trăng", "Đồng bằng sông Cửu Long", 9.6015, 105.9754, 72000, 1199653, 4200, 5500, 0.3, 2.6, ["Nông nghiệp", "Thủy sản"], 0.80, "high"),
    ("95", "Bạc Liêu", "Đồng bằng sông Cửu Long", 9.2941, 105.7278, 58000, 907236, 3800, 4500, 0.5, 2.2, ["Năng lượng", "Thủy sản"], 0.81, "medium"),
    ("96", "Cà Mau", "Đồng bằng sông Cửu Long", 9.1769, 105.1500, 92000, 1194476, 6500, 6800, 0.6, 2.4, ["Thủy sản", "Năng lượng"], 0.82, "medium"),
]

prov_data = []
for p in provinces:
    prov_data.append({
        "province_code": p[0],
        "province_name": p[1],
        "region": p[2],
        "gdp_billion_vnd": p[5],
        "population": p[6],
        "num_enterprises": p[7],
        "tax_revenue_billion_vnd": p[8],
        "fdi_billion_usd": p[9],
        "unemployment_rate": p[10],
        "dominant_sectors": p[11],
        "compliance_rate": p[12],
        "risk_level": p[13],
        "lat": p[3],
        "lng": p[4],
        "data_year": 2024
    })

with open(DATA_DIR / "vietnam_provinces.json", "w", encoding="utf-8") as f:
    json.dump(prov_data, f, ensure_ascii=False, indent=2)

# 2. Generate Historical Economic Events
events = [
    {
        "event_key": "covid19_wave1",
        "event_name": "COVID-19 First Wave",
        "event_name_vi": "Đại dịch COVID-19 Đợt 1",
        "event_type": "pandemic",
        "start_date": "2020-03-01",
        "end_date": "2020-09-30",
        "duration_months": 7,
        "severity": "high",
        "impact_gdp_pct": -3.5,
        "impact_tax_revenue_pct": -8.0,
        "impact_unemployment_pct": 1.5,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": -15.0,
        "affected_provinces": [],
        "affected_sectors": ["Du lịch & Khách sạn", "Vận tải & Logistics", "Thương mại"],
        "scope": "national",
        "description_vi": "Đợt bùng phát COVID-19 đầu tiên khiến kinh tế Việt Nam suy giảm, các hoạt động du lịch, dịch vụ đình trệ.",
        "source": "GSO/World Bank"
    },
    {
        "event_key": "covid19_wave4",
        "event_name": "COVID-19 Fourth Wave",
        "event_name_vi": "Đại dịch COVID-19 Đợt 4 (Delta)",
        "event_type": "pandemic",
        "start_date": "2021-04-27",
        "end_date": "2021-12-31",
        "duration_months": 8,
        "severity": "extreme",
        "impact_gdp_pct": -6.1,
        "impact_tax_revenue_pct": -12.5,
        "impact_unemployment_pct": 3.2,
        "impact_cpi_pct": 1.8,
        "impact_fdi_pct": -20.0,
        "affected_provinces": ["79", "74", "75", "01"], # HCM, Binh Duong, Dong Nai, HN
        "affected_sectors": ["Sản xuất", "Dịch vụ", "Thương mại", "Vận tải & Logistics"],
        "scope": "national",
        "description_vi": "Đợt bùng phát nghiêm trọng nhất với biến chủng Delta, dẫn đến phong tỏa diện rộng tại các trung tâm kinh tế lớn như TP.HCM, Bình Dương.",
        "source": "GSO"
    },
    {
        "event_key": "trade_war_us_cn",
        "event_name": "US-China Trade War",
        "event_name_vi": "Chiến tranh thương mại Mỹ-Trung",
        "event_type": "trade_war",
        "start_date": "2018-07-06",
        "end_date": None,
        "duration_months": 24,
        "severity": "medium",
        "impact_gdp_pct": 1.2,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.8,
        "impact_fdi_pct": 15.0,
        "affected_provinces": ["79", "27", "26", "31", "22", "74", "75"], # Provinces receiving FDI
        "affected_sectors": ["Sản xuất công nghiệp", "Xuất nhập khẩu"],
        "scope": "global",
        "description_vi": "Căng thẳng thương mại Mỹ-Trung khiến dòng vốn FDI và đơn hàng dịch chuyển sang Việt Nam, tạo ra cú hích tăng trưởng cho sản xuất công nghiệp và xuất khẩu.",
        "source": "Ministry of Planning and Investment"
    },
    {
        "event_key": "yagi_typhoon",
        "event_name": "Typhoon Yagi",
        "event_name_vi": "Siêu bão Yagi (Bão số 3)",
        "event_type": "natural_disaster",
        "start_date": "2024-09-06",
        "end_date": "2024-09-12",
        "duration_months": 1,
        "severity": "extreme",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.2,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["22", "31", "01", "26", "24", "19", "10", "15", "08"], # Quang Ninh, Hai Phong, HN, northern provinces
        "affected_sectors": ["Nông nghiệp", "Lâm nghiệp", "Du lịch", "Sản xuất"],
        "scope": "regional",
        "description_vi": "Siêu bão mạnh nhất trong nhiều thập kỷ đổ bộ vào miền Bắc, gây thiệt hại nặng nề về nông nghiệp, cơ sở hạ tầng, và đình trệ sản xuất tại nhiều khu công nghiệp.",
        "source": "VNDMA"
    },
    {
        "event_key": "cptpp_effective",
        "event_name": "CPTPP Enters into Force",
        "event_name_vi": "Hiệp định CPTPP có hiệu lực",
        "event_type": "trade_agreement",
        "start_date": "2019-01-14",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.7,
        "impact_tax_revenue_pct": 3.0,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 8.0,
        "affected_provinces": [],
        "affected_sectors": ["Dệt may", "Da giày", "Thủy sản", "Đồ gỗ"],
        "scope": "national",
        "description_vi": "Hiệp định CPTPP mở ra cơ hội lớn cho xuất khẩu của Việt Nam sang các thị trường mới, thúc đẩy cải cách thể chế và thu hút FDI.",
        "source": "MOIT"
    },
    {
        "event_key": "evfta_effective",
        "event_name": "EVFTA Enters into Force",
        "event_name_vi": "Hiệp định EVFTA có hiệu lực",
        "event_type": "trade_agreement",
        "start_date": "2020-08-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 2.4,
        "impact_tax_revenue_pct": 4.5,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 12.0,
        "affected_provinces": [],
        "affected_sectors": ["Dệt may", "Da giày", "Nông nghiệp", "Công nghệ"],
        "scope": "national",
        "description_vi": "Hiệp định thương mại tự do Việt Nam - EU loại bỏ phần lớn thuế quan, tạo lợi thế cạnh tranh rất lớn cho hàng hóa Việt Nam tại thị trường châu Âu.",
        "source": "MOIT"
    },
    {
        "event_key": "real_estate_crisis_2022",
        "event_name": "Real Estate Liquidity Crisis 2022-2023",
        "event_name_vi": "Khủng hoảng thanh khoản Bất động sản",
        "event_type": "financial_crisis",
        "start_date": "2022-10-01",
        "end_date": "2023-12-31",
        "duration_months": 15,
        "severity": "high",
        "impact_gdp_pct": -1.5,
        "impact_tax_revenue_pct": -5.5,
        "impact_unemployment_pct": 1.2,
        "impact_cpi_pct": 2.5,
        "impact_fdi_pct": -4.0,
        "affected_provinces": ["79", "01", "48", "74", "75", "56"],
        "affected_sectors": ["Bất động sản", "Xây dựng", "Vật liệu xây dựng", "Tài chính ngân hàng"],
        "scope": "national",
        "description_vi": "Sự kiện Vạn Thịnh Phát và việc siết chặt tín dụng, trái phiếu doanh nghiệp khiến thị trường bất động sản đóng băng, ảnh hưởng tiêu cực đến thu ngân sách từ tiền sử dụng đất.",
        "source": "Ministry of Finance"
    },
    {
        "event_key": "vat_reduction_2023",
        "event_name": "VAT Reduction Policy 2023",
        "event_name_vi": "Chính sách giảm thuế VAT 2%",
        "event_type": "policy",
        "start_date": "2023-07-01",
        "end_date": "2024-06-30",
        "duration_months": 12,
        "severity": "medium",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": -2.0,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": -0.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": [],
        "affected_sectors": ["Thương mại bán lẻ", "Dịch vụ", "Sản xuất"],
        "scope": "national",
        "description_vi": "Chính sách giảm thuế GTGT từ 10% xuống 8% giúp kích cầu tiêu dùng nội địa, hỗ trợ doanh nghiệp phục hồi sau đại dịch, dù làm giảm thu ngân sách ngắn hạn.",
        "source": "Ministry of Finance"
    },
    {
        "event_key": "samsung_fdi_expansion",
        "event_name": "Samsung FDI Expansion",
        "event_name_vi": "Samsung mở rộng đầu tư",
        "event_type": "growth",
        "start_date": "2014-01-01",
        "end_date": "2020-12-31",
        "duration_months": 84,
        "severity": "high",
        "impact_gdp_pct": 2.5,
        "impact_tax_revenue_pct": 5.0,
        "impact_unemployment_pct": -1.5,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 25.0,
        "affected_provinces": ["27", "19", "24"], # Bac Ninh, Thai Nguyen, Bac Giang
        "affected_sectors": ["Sản xuất điện tử", "Công nghệ cao", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "Samsung mở rộng mạnh mẽ các tổ hợp sản xuất tại Bắc Ninh và Thái Nguyên, biến Việt Nam thành cứ điểm sản xuất thiết bị di động lớn nhất thế giới của tập đoàn.",
        "source": "GSO"
    },
    {
        "event_key": "central_flood_2020",
        "event_name": "Historical Floods in Central Vietnam 2020",
        "event_name_vi": "Lũ lụt lịch sử miền Trung 2020",
        "event_type": "natural_disaster",
        "start_date": "2020-10-06",
        "end_date": "2020-11-15",
        "duration_months": 2,
        "severity": "high",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 2.0,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["42", "44", "45", "46", "49", "51"], # Ha Tinh, Quang Binh, Quang Tri, Hue, Quang Nam, Quang Ngai
        "affected_sectors": ["Nông nghiệp", "Cơ sở hạ tầng", "Thủy sản"],
        "scope": "regional",
        "description_vi": "Chuỗi bão và áp thấp nhiệt đới liên tiếp gây ngập lụt diện rộng, tàn phá cơ sở hạ tầng và sản xuất nông nghiệp tại các tỉnh miền Trung.",
        "source": "VNDMA"
    },
    {
        "event_key": "mekong_drought_salinity_2016",
        "event_name": "Mekong Delta Drought & Salinity 2016",
        "event_name_vi": "Hạn mặn lịch sử ĐBSCL 2016",
        "event_type": "natural_disaster",
        "start_date": "2015-12-01",
        "end_date": "2016-06-30",
        "duration_months": 7,
        "severity": "extreme",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.8,
        "impact_cpi_pct": 1.2,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["80", "82", "83", "84", "86", "87", "89", "91", "92", "93", "94", "95", "96"],
        "affected_sectors": ["Nông nghiệp", "Thủy sản", "Chế biến thực phẩm"],
        "scope": "regional",
        "description_vi": "Đợt hạn hán và ngập mặn khốc liệt nhất trong 100 năm tại Đồng bằng sông Cửu Long, phá hủy hàng trăm ngàn hecta lúa và gây thiệt hại kinh tế gần 450 triệu USD.",
        "source": "Ministry of Agriculture"
    },
    {
        "event_key": "formosa_disaster_2016",
        "event_name": "Formosa Environmental Disaster",
        "event_name_vi": "Thảm họa môi trường Formosa",
        "event_type": "natural_disaster",
        "start_date": "2016-04-01",
        "end_date": "2016-12-31",
        "duration_months": 9,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["42", "44", "45", "46"],
        "affected_sectors": ["Thủy sản", "Du lịch", "Dịch vụ ven biển"],
        "scope": "regional",
        "description_vi": "Sự cố xả thải độc hại làm cá chết hàng loạt dọc 200km bờ biển 4 tỉnh miền Trung, tàn phá nghiêm trọng ngành thủy sản và du lịch khu vực.",
        "source": "Government"
    },
    {
        "event_key": "african_swine_fever_2019",
        "event_name": "African Swine Fever Outbreak",
        "event_name_vi": "Dịch tả lợn Châu Phi",
        "event_type": "pandemic",
        "start_date": "2019-02-01",
        "end_date": "2020-06-30",
        "duration_months": 17,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 3.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": [],
        "affected_sectors": ["Nông nghiệp", "Chăn nuôi", "Chế biến thực phẩm"],
        "scope": "national",
        "description_vi": "Dịch bệnh quét sạch gần 20% tổng đàn lợn của Việt Nam, gây thiệt hại hàng tỷ USD và đẩy chỉ số giá tiêu dùng (CPI) tăng vọt do giá thịt lợn tăng phi mã.",
        "source": "Ministry of Agriculture"
    },
    {
        "event_key": "oil_price_collapse_2014",
        "event_name": "Global Oil Price Collapse",
        "event_name_vi": "Khủng hoảng giá dầu toàn cầu 2014",
        "event_type": "financial_crisis",
        "start_date": "2014-06-01",
        "end_date": "2015-12-31",
        "duration_months": 18,
        "severity": "high",
        "impact_gdp_pct": 0.2,
        "impact_tax_revenue_pct": -5.0,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": -1.5,
        "impact_fdi_pct": 1.0,
        "affected_provinces": ["72"],
        "affected_sectors": ["Dầu khí", "Khai khoáng", "Ngân sách Nhà nước"],
        "scope": "global",
        "description_vi": "Giá dầu thô giảm từ 100 USD xuống còn 50 USD/thùng làm thất thu nghiêm trọng ngân sách nhà nước (do thu từ dầu thô chiếm tỷ trọng lớn), dù giúp giảm chi phí sản xuất.",
        "source": "Ministry of Finance"
    },
    {
        "event_key": "russia_ukraine_conflict_2022",
        "event_name": "Russia-Ukraine Conflict",
        "event_name_vi": "Xung đột Nga - Ukraine",
        "event_type": "geopolitics",
        "start_date": "2022-02-24",
        "end_date": None,
        "duration_months": 48,
        "severity": "medium",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 2.5,
        "impact_fdi_pct": -0.5,
        "affected_provinces": [],
        "affected_sectors": ["Năng lượng", "Nông nghiệp", "Phân bón", "Logistics"],
        "scope": "global",
        "description_vi": "Gây gián đoạn chuỗi cung ứng toàn cầu, đẩy giá năng lượng, phân bón và nguyên vật liệu đầu vào tăng cao, ảnh hưởng lớn đến lạm phát nhập khẩu.",
        "source": "World Bank"
    },
    {
        "event_key": "red_sea_crisis_2024",
        "event_name": "Red Sea Shipping Crisis",
        "event_name_vi": "Khủng hoảng vận tải Biển Đỏ",
        "event_type": "geopolitics",
        "start_date": "2023-11-19",
        "end_date": None,
        "duration_months": 24,
        "severity": "medium",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.1,
        "impact_cpi_pct": 0.8,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["31", "79", "72"],
        "affected_sectors": ["Xuất nhập khẩu", "Logistics", "Cảng biển"],
        "scope": "global",
        "description_vi": "Các cuộc tấn công trên Biển Đỏ buộc tàu bè chuyển hướng, làm giá cước vận tải biển tăng vọt 300-400%, bào mòn lợi nhuận các doanh nghiệp xuất khẩu Việt Nam.",
        "source": "Vietnam Logistics Association"
    },
    {
        "event_key": "central_floods_1999",
        "event_name": "Historic Central Vietnam Floods 1999",
        "event_name_vi": "Lũ lụt lịch sử miền Trung 1999",
        "event_type": "natural_disaster",
        "start_date": "1999-11-01",
        "end_date": "1999-12-15",
        "duration_months": 2,
        "severity": "extreme",
        "impact_gdp_pct": -0.8,
        "impact_tax_revenue_pct": -1.5,
        "impact_unemployment_pct": 1.0,
        "impact_cpi_pct": 2.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["46", "49", "51", "52"],
        "affected_sectors": ["Nông nghiệp", "Cơ sở hạ tầng", "Giao thông"],
        "scope": "regional",
        "description_vi": "Trận lũ lụt tồi tệ nhất trong 40 năm tại miền Trung, tàn phá hàng vạn hecta lúa, làm chia cắt quốc lộ 1A và gây thiệt hại kinh tế lên đến 300 triệu USD (thời giá 1999).",
        "source": "UN/FAO"
    },
    {
        "event_key": "typhoon_damrey_2017",
        "event_name": "Typhoon Damrey 2017",
        "event_name_vi": "Bão số 12 (Damrey) 2017",
        "event_type": "natural_disaster",
        "start_date": "2017-11-04",
        "end_date": "2017-11-15",
        "duration_months": 1,
        "severity": "high",
        "impact_gdp_pct": -0.4,
        "impact_tax_revenue_pct": -0.8,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["56", "54"],
        "affected_sectors": ["Du lịch", "Nuôi trồng thủy sản", "Nhà ở"],
        "scope": "regional",
        "description_vi": "Cơn bão tàn phá dữ dội Nam Trung Bộ, đặc biệt là Khánh Hòa và Phú Yên, gây thiệt hại hơn 1 tỷ USD, đánh sập ngành nuôi trồng thủy sản và du lịch cục bộ.",
        "source": "World Bank"
    },
    {
        "event_key": "northern_power_shortage_2023",
        "event_name": "Northern Vietnam Power Shortage 2023",
        "event_name_vi": "Khủng hoảng thiếu điện miền Bắc 2023",
        "event_type": "infrastructure_shock",
        "start_date": "2023-05-15",
        "end_date": "2023-07-15",
        "duration_months": 2,
        "severity": "high",
        "impact_gdp_pct": -0.3,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["27", "24"],
        "affected_sectors": ["Sản xuất công nghiệp", "Công nghệ cao"],
        "scope": "regional",
        "description_vi": "Hạn hán và thiếu hụt nguồn cung điện dẫn đến cắt điện luân phiên tại các khu công nghiệp Bắc Ninh, Bắc Giang, gây thiệt hại khoảng 1.4 tỷ USD cho ngành sản xuất điện tử.",
        "source": "World Bank"
    },
    {
        "event_key": "hd981_oil_rig_crisis_2014",
        "event_name": "HD-981 Oil Rig Crisis & Riots",
        "event_name_vi": "Khủng hoảng Giàn khoan HD-981 & Bạo loạn 2014",
        "event_type": "geopolitics",
        "start_date": "2014-05-01",
        "end_date": "2014-07-15",
        "duration_months": 3,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.5,
        "impact_unemployment_pct": 0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": -5.0,
        "affected_provinces": ["74", "75", "42"],
        "affected_sectors": ["FDI", "Bất động sản công nghiệp", "Chứng khoán"],
        "scope": "regional",
        "description_vi": "Căng thẳng địa chính trị trên Biển Đông châm ngòi bạo loạn tại các khu công nghiệp Bình Dương, Đồng Nai, Hà Tĩnh, làm gián đoạn sản xuất và sụt giảm niềm tin FDI ngắn hạn.",
        "source": "VEPR"
    },
    {
        "event_key": "acb_banking_crisis_2012",
        "event_name": "ACB Banking Crisis (Bau Kien)",
        "event_name_vi": "Khủng hoảng Ngân hàng ACB 2012",
        "event_type": "financial_crisis",
        "start_date": "2012-08-20",
        "end_date": "2013-12-31",
        "duration_months": 16,
        "severity": "high",
        "impact_gdp_pct": -0.5,
        "impact_tax_revenue_pct": -1.0,
        "impact_unemployment_pct": 0.2,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": -1.0,
        "affected_provinces": ["79", "01"],
        "affected_sectors": ["Tài chính ngân hàng", "Chứng khoán"],
        "scope": "national",
        "description_vi": "Vụ bắt giữ Bầu Kiên gây chấn động hệ thống tài chính, dẫn đến làn sóng rút tiền hàng loạt tại ACB và thổi bay hàng tỷ USD vốn hóa trên thị trường chứng khoán.",
        "source": "State Bank of Vietnam"
    },
    {
        "event_key": "lego_fdi_binh_duong_2022",
        "event_name": "Lego $1B Green Investment",
        "event_name_vi": "Lego đầu tư 1 tỷ USD (FDI Xanh)",
        "event_type": "growth",
        "start_date": "2021-12-08",
        "end_date": "2025-04-09",
        "duration_months": 40,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 8.0,
        "affected_provinces": ["74"],
        "affected_sectors": ["Sản xuất đồ chơi", "Năng lượng tái tạo", "Logistics"],
        "scope": "regional",
        "description_vi": "Dự án nhà máy trung hòa carbon đầu tiên của Lego tại Bình Dương (VSIP III) trị giá 1.3 tỷ USD, tạo 4000 việc làm và thiết lập tiêu chuẩn mới cho FDI xanh tại Việt Nam.",
        "source": "Government"
    },
    {
        "event_key": "dung_quat_refinery_2005",
        "event_name": "Dung Quat Refinery Construction",
        "event_name_vi": "Khởi công Lọc hóa dầu Dung Quất",
        "event_type": "growth",
        "start_date": "2005-11-28",
        "end_date": "2009-02-22",
        "duration_months": 40,
        "severity": "extreme",
        "impact_gdp_pct": 1.2,
        "impact_tax_revenue_pct": 5.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["51"],
        "affected_sectors": ["Dầu khí", "Công nghiệp nặng", "Xây dựng"],
        "scope": "regional",
        "description_vi": "Nhà máy lọc dầu đầu tiên của Việt Nam tại Quảng Ngãi giúp đảm bảo an ninh năng lượng quốc gia, đóng góp tỷ trọng khổng lồ vào GDP và thu ngân sách của địa phương.",
        "source": "PetroVietnam"
    },
    {
        "event_key": "son_la_dam_2012",
        "event_name": "Son La Hydropower Plant Opening",
        "event_name_vi": "Khánh thành Thủy điện Sơn La",
        "event_type": "growth",
        "start_date": "2012-12-23",
        "end_date": "2015-12-31",
        "duration_months": 36,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 3.0,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 0.5,
        "affected_provinces": ["14", "11", "12"],
        "affected_sectors": ["Năng lượng", "Xây dựng", "Nuôi trồng thủy sản"],
        "scope": "regional",
        "description_vi": "Nhà máy thủy điện lớn nhất Đông Nam Á đi vào hoạt động không chỉ đảm bảo an ninh năng lượng quốc gia mà còn tạo cú hích lịch sử cho GRDP và thu ngân sách của Sơn La, Lai Châu, Điện Biên.",
        "source": "EVN"
    },
    {
        "event_key": "coffee_price_boom_2024",
        "event_name": "Central Highlands Coffee Boom 2024",
        "event_name_vi": "Kỷ lục giá Cà phê Tây Nguyên 2024",
        "event_type": "growth",
        "start_date": "2023-11-01",
        "end_date": "2025-05-30",
        "duration_months": 18,
        "severity": "high",
        "impact_gdp_pct": 0.4,
        "impact_tax_revenue_pct": 1.5,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.3,
        "impact_fdi_pct": 1.0,
        "affected_provinces": ["66", "67", "68", "64", "62"],
        "affected_sectors": ["Nông nghiệp", "Xuất khẩu", "Bán lẻ nội vùng"],
        "scope": "regional",
        "description_vi": "Giá cà phê Robusta vượt 130,000 VNĐ/kg mang lại doanh thu xuất khẩu kỷ lục 8.4 tỷ USD, tạo ra sự bùng nổ tiêu dùng và dòng tiền tái đầu tư tại các tỉnh Tây Nguyên (đặc biệt Đắk Lắk, Lâm Đồng).",
        "source": "Ministry of Agriculture"
    },
    {
        "event_key": "vinfast_hai_phong_2017",
        "event_name": "VinFast Dinh Vu Manufacturing Complex",
        "event_name_vi": "Khởi công Tổ hợp VinFast Hải Phòng",
        "event_type": "growth",
        "start_date": "2017-09-02",
        "end_date": "2021-12-31",
        "duration_months": 51,
        "severity": "extreme",
        "impact_gdp_pct": 0.6,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.8,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 4.0,
        "affected_provinces": ["31"],
        "affected_sectors": ["Sản xuất ô tô", "Công nghiệp phụ trợ", "Logistics"],
        "scope": "regional",
        "description_vi": "Tổ hợp sản xuất ô tô quy mô lớn đầu tiên của Việt Nam tại Đình Vũ tạo ra hệ sinh thái công nghiệp phụ trợ khổng lồ, đóng vai trò cực kỳ quan trọng trong GRDP của Hải Phòng.",
        "source": "Government"
    },
    {
        "event_key": "can_tho_bridge_2010",
        "event_name": "Can Tho Bridge Inauguration",
        "event_name_vi": "Khánh thành Cầu Cần Thơ",
        "event_type": "growth",
        "start_date": "2010-04-24",
        "end_date": "2015-12-31",
        "duration_months": 68,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.2,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["92", "86", "93", "89", "91"],
        "affected_sectors": ["Giao thông", "Thương mại", "Nông nghiệp", "Du lịch"],
        "scope": "regional",
        "description_vi": "Xóa bỏ nút thắt phà Cần Thơ, cây cầu kết nối huyết mạch Quốc lộ 1A giúp vận tải nông thủy sản ĐBSCL thông suốt, biến Cần Thơ thành cực tăng trưởng thương mại dịch vụ toàn vùng.",
        "source": "Ministry of Transport"
    },
    {
        "event_key": "border_closure_covid_2021",
        "event_name": "China Border Closure Crisis 2021",
        "event_name_vi": "Khủng hoảng đóng biên Việt-Trung 2021",
        "event_type": "geopolitics",
        "start_date": "2021-12-01",
        "end_date": "2022-04-30",
        "duration_months": 5,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": -0.4,
        "impact_unemployment_pct": 0.3,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 0.0,
        "affected_provinces": ["20", "10", "22"],
        "affected_sectors": ["Xuất nhập khẩu", "Logistics biên mậu", "Nông nghiệp"],
        "scope": "regional",
        "description_vi": "Chính sách Zero-Covid của Trung Quốc làm ùn ứ hàng ngàn xe container nông sản tại các cửa khẩu Lạng Sơn, Lào Cai, Quảng Ninh, gây thiệt hại nghiêm trọng cho chuỗi cung ứng biên mậu.",
        "source": "Customs Department"
    },
    {
        "event_key": "phu_quoc_island_city_2021",
        "event_name": "Phu Quoc Becomes First Island City",
        "event_name_vi": "Thành lập Thành phố Đảo Phú Quốc",
        "event_type": "policy",
        "start_date": "2021-01-01",
        "end_date": "2024-12-31",
        "duration_months": 48,
        "severity": "high",
        "impact_gdp_pct": 0.3,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 1.5,
        "impact_fdi_pct": 3.0,
        "affected_provinces": ["91"],
        "affected_sectors": ["Du lịch", "Bất động sản", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "Phú Quốc lên thành phố kéo theo dòng vốn đầu tư khổng lồ vào hạ tầng du lịch và bất động sản nghỉ dưỡng, đóng góp tỷ trọng lớn vào ngân sách tỉnh Kiên Giang nhưng cũng gây áp lực lạm phát cục bộ.",
        "source": "Government"
    },
    {
        "event_key": "doi_moi_1986",
        "event_name": "Doi Moi (Economic Renovation)",
        "event_name_vi": "Cải cách kinh tế Đổi Mới",
        "event_type": "policy",
        "start_date": "1986-12-01",
        "end_date": "1995-12-31",
        "duration_months": 108,
        "severity": "extreme",
        "impact_gdp_pct": 5.0,
        "impact_tax_revenue_pct": 8.0,
        "impact_unemployment_pct": -2.0,
        "impact_cpi_pct": -50.0,
        "impact_fdi_pct": 100.0,
        "affected_provinces": [],
        "affected_sectors": ["Nông nghiệp", "Sản xuất", "Thương mại", "Dịch vụ"],
        "scope": "national",
        "description_vi": "Chính sách Đổi Mới chuyển đổi nền kinh tế từ kế hoạch hóa tập trung sang kinh tế thị trường định hướng XHCN, mở cửa thương mại và thu hút đầu tư.",
        "source": "Government/World Bank"
    },
    {
        "event_key": "asian_financial_crisis_1997",
        "event_name": "Asian Financial Crisis",
        "event_name_vi": "Khủng hoảng tài chính Châu Á",
        "event_type": "financial_crisis",
        "start_date": "1997-07-02",
        "end_date": "1999-12-31",
        "duration_months": 30,
        "severity": "medium",
        "impact_gdp_pct": -2.5,
        "impact_tax_revenue_pct": -4.0,
        "impact_unemployment_pct": 1.0,
        "impact_cpi_pct": 2.0,
        "impact_fdi_pct": -10.0,
        "affected_provinces": [],
        "affected_sectors": ["Xuất nhập khẩu", "Đầu tư nước ngoài", "Tài chính"],
        "scope": "regional",
        "description_vi": "Khủng hoảng tài chính bắt nguồn từ Thái Lan ảnh hưởng đến luồng vốn FDI và xuất khẩu của Việt Nam, mặc dù Việt Nam ít bị tổn thương hơn do thị trường tài chính chưa mở cửa hoàn toàn.",
        "source": "IMF/World Bank"
    },
    {
        "event_key": "us_vn_bta_2000",
        "event_name": "US-Vietnam Bilateral Trade Agreement",
        "event_name_vi": "Hiệp định Thương mại Song phương Việt-Mỹ (BTA)",
        "event_type": "trade_agreement",
        "start_date": "2001-12-10",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 3.0,
        "impact_unemployment_pct": -1.0,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 15.0,
        "affected_provinces": [],
        "affected_sectors": ["Dệt may", "Da giày", "Thủy sản", "Đồ gỗ"],
        "scope": "national",
        "description_vi": "BTA bình thường hóa quan hệ thương mại, mở ra thị trường khổng lồ cho xuất khẩu Việt Nam và đánh dấu bước hội nhập quốc tế quan trọng.",
        "source": "MOIT"
    },
    {
        "event_key": "wto_accession_2007",
        "event_name": "WTO Accession",
        "event_name_vi": "Gia nhập WTO",
        "event_type": "trade_agreement",
        "start_date": "2007-01-11",
        "end_date": None,
        "duration_months": 120,
        "severity": "extreme",
        "impact_gdp_pct": 2.0,
        "impact_tax_revenue_pct": 4.0,
        "impact_unemployment_pct": -1.5,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": 20.0,
        "affected_provinces": [],
        "affected_sectors": ["Sản xuất công nghiệp", "Dịch vụ", "Tài chính ngân hàng", "Bán lẻ"],
        "scope": "national",
        "description_vi": "Việt Nam chính thức trở thành thành viên thứ 150 của WTO, tạo cú hích lịch sử cho FDI và xuất khẩu, đồng thời đặt ra thách thức cạnh tranh gay gắt.",
        "source": "WTO/GSO"
    },
    {
        "event_key": "global_financial_crisis_2008",
        "event_name": "Global Financial Crisis",
        "event_name_vi": "Khủng hoảng tài chính toàn cầu",
        "event_type": "financial_crisis",
        "start_date": "2008-09-01",
        "end_date": "2010-12-31",
        "duration_months": 28,
        "severity": "high",
        "impact_gdp_pct": -3.0,
        "impact_tax_revenue_pct": -6.0,
        "impact_unemployment_pct": 2.0,
        "impact_cpi_pct": 5.0,
        "impact_fdi_pct": -12.0,
        "affected_provinces": [],
        "affected_sectors": ["Tài chính ngân hàng", "Bất động sản", "Xuất khẩu"],
        "scope": "global",
        "description_vi": "Khủng hoảng kinh tế thế giới làm giảm cầu xuất khẩu và vốn FDI, đồng thời gói kích cầu trong nước gây ra hệ lụy lạm phát cao sau đó.",
        "source": "Ministry of Finance"
    },
    {
        "event_key": "high_inflation_2011",
        "event_name": "High Inflation & Monetary Tightening",
        "event_name_vi": "Lạm phát phi mã và Thắt chặt tiền tệ",
        "event_type": "financial_crisis",
        "start_date": "2011-01-01",
        "end_date": "2012-12-31",
        "duration_months": 24,
        "severity": "high",
        "impact_gdp_pct": -1.8,
        "impact_tax_revenue_pct": -3.5,
        "impact_unemployment_pct": 1.2,
        "impact_cpi_pct": 18.6,
        "impact_fdi_pct": -5.0,
        "affected_provinces": [],
        "affected_sectors": ["Ngân hàng", "Bất động sản", "Xây dựng", "Sản xuất"],
        "scope": "national",
        "description_vi": "Lạm phát đạt mức 18.6% (2011), buộc NHNN áp dụng chính sách thắt chặt tiền tệ (Nghị quyết 11), khiến lãi suất tăng vọt và đóng băng bất động sản.",
        "source": "SBV/GSO"
    },
    {
        "event_key": "scb_vtp_crisis_2022",
        "event_name": "SCB & Van Thinh Phat Crisis",
        "event_name_vi": "Khủng hoảng SCB & Vạn Thịnh Phát",
        "event_type": "financial_crisis",
        "start_date": "2022-10-08",
        "end_date": "2024-12-31",
        "duration_months": 26,
        "severity": "extreme",
        "impact_gdp_pct": -1.2,
        "impact_tax_revenue_pct": -4.0,
        "impact_unemployment_pct": 0.8,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": -2.0,
        "affected_provinces": ["79", "01"],
        "affected_sectors": ["Tài chính ngân hàng", "Bất động sản", "Trái phiếu doanh nghiệp"],
        "scope": "national",
        "description_vi": "Vụ án thao túng ngân hàng SCB và phát hành trái phiếu khống của Vạn Thịnh Phát gây chấn động hệ thống ngân hàng, buộc NHNN can thiệp bơm thanh khoản quy mô lớn.",
        "source": "SBV/Ministry of Public Security"
    },
    {
        "event_key": "global_minimum_tax_2024",
        "event_name": "Global Minimum Tax (Pillar Two)",
        "event_name_vi": "Thuế tối thiểu toàn cầu 15%",
        "event_type": "policy",
        "start_date": "2024-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": -0.2,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": -1.5,
        "affected_provinces": ["27", "19", "24", "79", "31", "01", "26", "22"],
        "affected_sectors": ["FDI", "Công nghệ cao", "Sản xuất điện tử"],
        "scope": "national",
        "description_vi": "Áp dụng thuế bổ sung (QDMTT) 15% đối với các tập đoàn đa quốc gia lớn, làm vô hiệu hóa nhiều ưu đãi thuế cũ, buộc Việt Nam phải chuyển hướng cạnh tranh thu hút FDI.",
        "source": "Ministry of Finance/OECD"
    },
    {
        "event_key": "semiconductor_fdi_boom_2024",
        "event_name": "Semiconductor FDI Boom",
        "event_name_vi": "Làn sóng FDI ngành Bán dẫn",
        "event_type": "growth",
        "start_date": "2024-01-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 1.5,
        "impact_tax_revenue_pct": 2.0,
        "impact_unemployment_pct": -0.5,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 12.0,
        "affected_provinces": ["01", "79", "31", "27", "24"],
        "affected_sectors": ["Công nghệ cao", "Bán dẫn", "AI", "Giáo dục đào tạo"],
        "scope": "regional",
        "description_vi": "Việt Nam đón nhận làn sóng đầu tư mạnh mẽ vào thiết kế, đóng gói và kiểm thử bán dẫn từ các tập đoàn lớn (Amkor, NVIDIA) theo định hướng chiến lược quốc gia.",
        "source": "Ministry of Planning and Investment"
    },
    {
        "event_key": "us_tariffs_shock_2025",
        "event_name": "US Tariffs Policy 2025",
        "event_name_vi": "Cú sốc thuế quan từ Mỹ 2025",
        "event_type": "trade_war",
        "start_date": "2025-04-01",
        "end_date": "2026-12-31",
        "duration_months": 21,
        "severity": "high",
        "impact_gdp_pct": -1.8,
        "impact_tax_revenue_pct": -3.5,
        "impact_unemployment_pct": 1.5,
        "impact_cpi_pct": 1.2,
        "impact_fdi_pct": -4.0,
        "affected_provinces": ["79", "27", "24", "31", "34", "36"],
        "affected_sectors": ["Dệt may", "Gỗ", "Điện tử", "Lốp xe", "Pin năng lượng mặt trời"],
        "scope": "national",
        "description_vi": "Mỹ áp thuế suất 20% chung và 40% đối với hàng hóa nghi chuyển tải từ nước thứ 3, gây áp lực lớn lên xuất khẩu và chuỗi cung ứng của Việt Nam.",
        "source": "MOIT/USTR"
    },
    {
        "event_key": "rare_earth_export_ban_2025",
        "event_name": "Rare Earth Export Suspension",
        "event_name_vi": "Tạm ngừng xuất khẩu Đất hiếm",
        "event_type": "policy",
        "start_date": "2025-12-01",
        "end_date": None,
        "duration_months": 24,
        "severity": "medium",
        "impact_gdp_pct": 0.2,
        "impact_tax_revenue_pct": 0.5,
        "impact_unemployment_pct": 0.0,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 2.0,
        "affected_provinces": ["12", "10", "15", "08"],
        "affected_sectors": ["Khai khoáng", "Công nghệ cao"],
        "scope": "regional",
        "description_vi": "Chính sách hạn chế xuất khẩu quặng thô đất hiếm nhằm bảo vệ tài nguyên chiến lược và thu hút đầu tư công nghệ chế biến sâu vào Việt Nam.",
        "source": "Government"
    },
    {
        "event_key": "china_plus_one_shift",
        "event_name": "China Plus One Strategy",
        "event_name_vi": "Dịch chuyển chuỗi cung ứng Trung Quốc+1",
        "event_type": "growth",
        "start_date": "2018-01-01",
        "end_date": None,
        "duration_months": 120,
        "severity": "high",
        "impact_gdp_pct": 1.8,
        "impact_tax_revenue_pct": 3.2,
        "impact_unemployment_pct": -1.2,
        "impact_cpi_pct": 0.5,
        "impact_fdi_pct": 18.0,
        "affected_provinces": ["24", "27", "31", "33", "26", "22"],
        "affected_sectors": ["Sản xuất", "Khu công nghiệp", "Logistics"],
        "scope": "national",
        "description_vi": "Làn sóng dịch chuyển nhà máy từ Trung Quốc sang Việt Nam để đa dạng hóa chuỗi cung ứng và giảm thiểu rủi ro địa chính trị.",
        "source": "World Bank/FDI Reports"
    },
    {
        "event_key": "land_law_2024_effective",
        "event_name": "Land Law 2024 Effective",
        "event_name_vi": "Luật Đất đai 2024 có hiệu lực",
        "event_type": "policy",
        "start_date": "2024-08-01",
        "end_date": None,
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.8,
        "impact_tax_revenue_pct": 2.5,
        "impact_unemployment_pct": -0.3,
        "impact_cpi_pct": 1.0,
        "impact_fdi_pct": 1.5,
        "affected_provinces": [],
        "affected_sectors": ["Bất động sản", "Xây dựng", "Nông nghiệp"],
        "scope": "national",
        "description_vi": "Luật Đất đai mới bỏ khung giá đất, áp dụng bảng giá đất sát thị trường, giúp minh bạch hóa thị trường nhưng cũng làm tăng chi phí giải phóng mặt bằng.",
        "source": "National Assembly"
    },
    {
        "event_key": "aec_establishment_2015",
        "event_name": "ASEAN Economic Community",
        "event_name_vi": "Thành lập Cộng đồng Kinh tế ASEAN (AEC)",
        "event_type": "trade_agreement",
        "start_date": "2015-12-31",
        "end_date": None,
        "duration_months": 120,
        "severity": "medium",
        "impact_gdp_pct": 0.6,
        "impact_tax_revenue_pct": 1.2,
        "impact_unemployment_pct": -0.4,
        "impact_cpi_pct": 0.2,
        "impact_fdi_pct": 3.0,
        "affected_provinces": [],
        "affected_sectors": ["Thương mại", "Lao động", "Dịch vụ"],
        "scope": "regional",
        "description_vi": "AEC tạo ra thị trường chung và cơ sở sản xuất thống nhất cho 10 nước ASEAN, tăng cường dòng chảy tự do của hàng hóa, dịch vụ và lao động có tay nghề.",
        "source": "ASEAN Secretariat"
    },
    {
        "event_key": "fdi_intel_2006",
        "event_name": "Intel Invests in Vietnam",
        "event_name_vi": "Intel đầu tư nhà máy tỷ đô",
        "event_type": "growth",
        "start_date": "2006-02-28",
        "end_date": "2010-12-31",
        "duration_months": 60,
        "severity": "high",
        "impact_gdp_pct": 0.5,
        "impact_tax_revenue_pct": 1.0,
        "impact_unemployment_pct": -0.2,
        "impact_cpi_pct": 0.1,
        "impact_fdi_pct": 5.0,
        "affected_provinces": ["79"],
        "affected_sectors": ["Công nghệ cao", "Sản xuất điện tử"],
        "scope": "national",
        "description_vi": "Quyết định đầu tư nhà máy lắp ráp và kiểm định chip 1 tỷ USD của Intel tại TP.HCM là bước ngoặt đánh dấu sự xuất hiện của Việt Nam trên bản đồ công nghệ cao toàn cầu.",
        "source": "MPI"
    }
]

with open(DATA_DIR / "historical_economic_events.json", "w", encoding="utf-8") as f:
    # TRY TO IMPORT EXTERNAL EVENTS TO AVOID LOSING THEM
    try:
        from expand_macro_events_v2 import all_new_events
        events.extend(all_new_events)
    except ImportError:
        pass
        
    try:
        from expand_macro_events import new_events, generate_province_events
        events.extend(new_events)
        events.extend(generate_province_events())
    except ImportError:
        pass
        
    # Remove duplicates by event_key
    unique_events = []
    seen_keys = set()
    for e in events:
        if e["event_key"] not in seen_keys:
            unique_events.append(e)
            seen_keys.add(e["event_key"])

    json.dump(unique_events, f, ensure_ascii=False, indent=2)

print(f"Macro data generated successfully with {len(unique_events) if 'unique_events' in locals() else len(events)} events.")
