LEGAL_DEEP_DATA_NEW = [
    # 1. Thuế GTGT — Thời hạn khai nộp
    {
        "q": "Thời hạn nộp hồ sơ khai thuế GTGT theo tháng là ngày nào?",
        "tool_query": "Luật Quản lý thuế 38/2019/QH14 Điều 44 thời hạn nộp hồ sơ khai thuế tháng",
        "doc_title": "Luật Quản lý thuế 38/2019/QH14",
        "doc_snippet": "Chậm nhất là ngày thứ 20 của tháng tiếp theo tháng phát sinh nghĩa vụ thuế đối với trường hợp khai và nộp theo tháng.",
        "answer": "Căn cứ theo quy định tại **Điều 44 Luật Quản lý thuế số 38/2019/QH14**, thời hạn nộp hồ sơ khai thuế Giá trị gia tăng (GTGT) được quy định như sau:\n\n**1. Đối với doanh nghiệp khai thuế theo tháng:**\nThời hạn nộp hồ sơ khai thuế GTGT chậm nhất là **ngày thứ 20 của tháng tiếp theo** tháng phát sinh nghĩa vụ thuế.\n\n*Ví dụ:* Thời hạn nộp hồ sơ khai thuế GTGT của tháng 05/2024 chậm nhất là ngày 20/06/2024.\n\n**2. Xử lý khi trùng ngày nghỉ:**\nTrường hợp ngày cuối cùng của thời hạn nộp hồ sơ khai thuế trùng với ngày nghỉ cuối tuần hoặc ngày nghỉ lễ theo quy định, thì ngày cuối cùng của thời hạn nộp hồ sơ khai thuế là ngày làm việc liền kề sau ngày nghỉ đó.\n\n**Lưu ý:** Việc chậm nộp tờ khai thuế sẽ bị xử phạt vi phạm hành chính về thuế theo Nghị định 125/2020/NĐ-CP. Doanh nghiệp cần lưu ý thời hạn để tránh phát sinh tiền phạt không đáng có."
    },
    {
        "q": "Thời hạn nộp tờ khai thuế GTGT quý là bao giờ?",
        "tool_query": "Luật Quản lý thuế 38/2019/QH14 Điều 44 thời hạn khai thuế quý",
        "doc_title": "Luật Quản lý thuế 38/2019/QH14",
        "doc_snippet": "Chậm nhất là ngày cuối cùng của tháng đầu của quý tiếp theo quý phát sinh nghĩa vụ thuế đối với trường hợp khai và nộp theo quý.",
        "answer": "Theo quy định tại **Khoản 1 Điều 44 Luật Quản lý thuế số 38/2019/QH14**, thời hạn nộp hồ sơ khai thuế Giá trị gia tăng (GTGT) theo quý được thực hiện như sau:\n\n**1. Thời hạn nộp hồ sơ khai thuế theo quý:**\nChậm nhất là **ngày cuối cùng của tháng đầu tiên của quý tiếp theo** quý phát sinh nghĩa vụ thuế.\n\n*Ví dụ cụ thể:* \n- Tờ khai GTGT Quý I (tháng 1, 2, 3): Hạn chót là ngày 30/04 (nếu 30/04 là ngày lễ thì lùi sang ngày làm việc tiếp theo).\n- Tờ khai GTGT Quý II (tháng 4, 5, 6): Hạn chót là ngày 31/07.\n\n**2. Thời hạn nộp tiền thuế:**\nCăn cứ Điều 55 Luật Quản lý thuế 38/2019/QH14, thời hạn nộp tiền thuế chậm nhất là **ngày cuối cùng của thời hạn nộp hồ sơ khai thuế**.\n\n**Khuyến nghị:** Kế toán cần thiết lập lịch nhắc nhở nộp tờ khai trước hạn từ 3-5 ngày để phòng ngừa các sự cố về mạng, chữ ký số hết hạn hoặc lỗi hệ thống eTax của Cơ quan thuế."
    },
    {
        "q": "Điều kiện nào để doanh nghiệp được khai thuế GTGT theo quý?",
        "tool_query": "Thông tư 80/2021/TT-BTC Điều 9 điều kiện khai thuế GTGT theo quý",
        "doc_title": "Thông tư 80/2021/TT-BTC",
        "doc_snippet": "Khai thuế GTGT theo quý áp dụng đối với người nộp thuế có tổng doanh thu bán hàng hoá và cung cấp dịch vụ của năm trước liền kề từ 50 tỷ đồng trở xuống.",
        "answer": "Căn cứ theo quy định tại **Điều 9 Thông tư 80/2021/TT-BTC** và **Điều 8 Nghị định 126/2020/NĐ-CP**, điều kiện để doanh nghiệp được lựa chọn khai thuế Giá trị gia tăng (GTGT) theo quý được xác định như sau:\n\n**1. Tiêu chí doanh thu:**\nKhai thuế theo quý áp dụng đối với người nộp thuế đáp ứng điều kiện có tổng doanh thu bán hàng hoá và cung cấp dịch vụ của năm trước liền kề **từ 50 tỷ đồng trở xuống**.\n\n**2. Đối với doanh nghiệp mới thành lập:**\nNgười nộp thuế mới bắt đầu hoạt động sản xuất kinh doanh thì việc khai thuế GTGT được thực hiện **theo quý**.\nSau khi sản xuất kinh doanh đủ 12 tháng, từ năm dương lịch tiếp theo, sẽ căn cứ theo mức doanh thu bán hàng hoá, dịch vụ của năm dương lịch trước liền kề (đủ 12 tháng) để quyết định khai theo tháng hay theo quý.\n\n**3. Cách thức thay đổi kỳ tính thuế:**\nTrường hợp người nộp thuế đủ điều kiện và lựa chọn khai thuế theo quý, người nộp thuế gửi văn bản đề nghị (Mẫu 01/ĐK-TĐK) đến cơ quan thuế chậm nhất là **ngày 31 tháng 01** của năm bắt đầu khai thuế theo quý.\n\n**Lưu ý:** Việc xác định kỳ tính thuế GTGT theo tháng hoặc theo quý được áp dụng ổn định trọn năm dương lịch."
    },

    # 2. Hoàn thuế GTGT
    {
        "q": "Điều kiện để dự án đầu tư được hoàn thuế GTGT là gì?",
        "tool_query": "Thông tư 80/2021/TT-BTC Điều 28 hoàn thuế GTGT dự án đầu tư",
        "doc_title": "Thông tư 80/2021/TT-BTC",
        "doc_snippet": "Cơ sở kinh doanh đang hoạt động có dự án đầu tư mới có số thuế GTGT đầu vào chưa được khấu trừ hết từ 300 triệu đồng trở lên thì được hoàn thuế.",
        "answer": "Dựa trên quy định tại **Khoản 2 Điều 13 Luật Thuế GTGT 2008 (sửa đổi, bổ sung bởi Luật 106/2016/QH13)** và hướng dẫn chi tiết tại **Thông tư 80/2021/TT-BTC**, điều kiện hoàn thuế GTGT cho dự án đầu tư được quy định như sau:\n\n**1. Mức thuế đầu vào chưa khấu trừ:**\nCơ sở kinh doanh đang hoạt động, có dự án đầu tư mới (trừ dự án đầu tư xây dựng nhà để bán hoặc cho thuê mà không hình thành tài sản cố định) tại địa bàn cùng tỉnh/thành phố hoặc khác tỉnh/thành phố, đang trong giai đoạn đầu tư, có số thuế GTGT đầu vào của hàng hóa, dịch vụ phát sinh trong giai đoạn đầu tư chưa được khấu trừ hết từ **300 triệu đồng trở lên** thì được hoàn thuế GTGT.\n\n**2. Hồ sơ hoàn thuế:**\n- Giấy đề nghị hoàn trả khoản thu ngân sách nhà nước (Mẫu 01/HT).\n- Bản sao Giấy chứng nhận đầu tư/Quyết định chủ trương đầu tư.\n- Bảng kê hóa đơn, chứng từ hàng hóa dịch vụ mua vào.\n\n**3. Trường hợp KHÔNG được hoàn thuế dự án đầu tư:**\n- Dự án đầu tư của cơ sở kinh doanh không góp đủ số vốn điều lệ như đã đăng ký.\n- Dự án đầu tư của cơ sở kinh doanh ngành, nghề đầu tư kinh doanh có điều kiện khi chưa đủ các điều kiện kinh doanh.\n\n**Lưu ý:** Cơ sở kinh doanh phải thực hiện kê khai riêng thuế GTGT của dự án đầu tư trên tờ khai 02/GTGT và bù trừ với số thuế GTGT phải nộp của hoạt động sản xuất kinh doanh đang thực hiện."
    },
    {
        "q": "Hoàn thuế GTGT hàng hóa xuất khẩu quy định thế nào?",
        "tool_query": "Luật 106/2016/QH13 hoàn thuế GTGT xuất khẩu",
        "doc_title": "Luật thuế GTGT số 106/2016/QH13",
        "doc_snippet": "Cơ sở kinh doanh trong tháng, quý có hàng hoá, dịch vụ xuất khẩu nếu có số thuế GTGT đầu vào chưa được khấu trừ từ 300 triệu đồng trở lên thì được hoàn thuế GTGT.",
        "answer": "Căn cứ **Khoản 3 Điều 1 Luật số 106/2016/QH13** sửa đổi, bổ sung một số điều của Luật thuế GTGT, việc hoàn thuế GTGT đối với hàng hóa, dịch vụ xuất khẩu được quy định như sau:\n\n**1. Điều kiện về số tiền thuế:**\nCơ sở kinh doanh trong tháng, quý có hàng hoá, dịch vụ xuất khẩu nếu có số thuế GTGT đầu vào chưa được khấu trừ từ **300 triệu đồng trở lên** thì được hoàn thuế GTGT theo tháng, quý. Nếu số thuế chưa khấu trừ dưới 300 triệu đồng thì được kết chuyển sang tháng, quý tiếp theo.\n\n**2. Mức hoàn tối đa:**\nSố thuế GTGT được hoàn đối với hàng hóa, dịch vụ xuất khẩu **không vượt quá doanh thu** của hàng hóa, dịch vụ xuất khẩu nhân (x) với **10%**.\n\n**3. Điều kiện bắt buộc để được hoàn:**\n- Phải có hợp đồng bán hàng hóa, gia công hàng hóa đối với tổ chức, cá nhân nước ngoài.\n- Có tờ khai hải quan đối với hàng hóa xuất khẩu đã làm xong thủ tục hải quan.\n- Hàng hóa, dịch vụ xuất khẩu phải thanh toán qua ngân hàng.\n- Phải có hóa đơn GTGT hoặc hóa đơn bán hàng.\n\n**Khuyến nghị:** Cơ quan thuế quản lý rất chặt chẽ việc hoàn thuế khâu xuất khẩu (đặc biệt đối với xuất khẩu nông lâm thủy sản, gỗ, linh kiện điện tử). Doanh nghiệp cần đảm bảo hồ sơ truy xuất nguồn gốc hàng hóa đầy đủ, minh bạch."
    },
    {
        "q": "Có những hình thức kiểm tra hồ sơ hoàn thuế nào?",
        "tool_query": "Thông tư 80/2021/TT-BTC Điều 33 phân loại hồ sơ hoàn thuế",
        "doc_title": "Thông tư 80/2021/TT-BTC",
        "doc_snippet": "Hồ sơ hoàn thuế được phân loại thành hồ sơ thuộc diện hoàn thuế trước, kiểm tra sau và hồ sơ thuộc diện kiểm tra trước, hoàn thuế sau.",
        "answer": "Căn cứ **Điều 73 Luật Quản lý thuế 38/2019/QH14** và **Điều 33 Thông tư 80/2021/TT-BTC**, hồ sơ hoàn thuế GTGT được phân loại thành 02 diện sau:\n\n**1. Diện hoàn thuế trước, kiểm tra sau:**\nÁp dụng đối với người nộp thuế chấp hành tốt pháp luật về thuế và hồ sơ hoàn thuế rủi ro thấp. Cơ quan thuế ra quyết định hoàn thuế trong vòng **06 ngày làm việc** kể từ ngày nhận đủ hồ sơ, sau đó mới lên kế hoạch thanh tra, kiểm tra tại trụ sở người nộp thuế.\n\n**2. Diện kiểm tra trước, hoàn thuế sau:**\nCơ quan thuế sẽ tiến hành kiểm tra trực tiếp tại doanh nghiệp trước khi ra quyết định hoàn tiền (thời hạn giải quyết tối đa **40 ngày**). Áp dụng trong các trường hợp:\n- Hoàn thuế lần đầu của từng trường hợp hoàn thuế.\n- Người nộp thuế có hành vi trốn thuế, gian lận thuế trong vòng 02 năm trước đó.\n- Hàng hóa xuất khẩu nhập khẩu không thanh toán qua ngân hàng thương mại.\n- Doanh nghiệp rủi ro cao về thuế.\n- Hồ sơ hoàn thuế thuộc diện hoàn trước, kiểm tra sau nhưng quá thời hạn giải trình mà người nộp thuế không giải trình hoặc giải trình không chứng minh được tính chính xác của hồ sơ.\n\n**Khuyến nghị:** Để được xét vào diện 'Hoàn trước, kiểm tra sau', doanh nghiệp cần duy trì lịch sử tuân thủ thuế tốt, không có nợ đọng thuế, và cung cấp hồ sơ đầy đủ, minh bạch ngay từ lần nộp đầu tiên."
    },

    # 3. Thuế TNCN — Biểu thuế lũy tiến
    {
        "q": "Biểu thuế thu nhập cá nhân lũy tiến từng phần hiện nay quy định thế nào?",
        "tool_query": "Luật Thuế TNCN biểu thuế lũy tiến từng phần",
        "doc_title": "Luật Thuế Thu nhập cá nhân",
        "doc_snippet": "Biểu thuế lũy tiến từng phần gồm 7 bậc, từ 5% đến 35%, áp dụng đối với thu nhập từ tiền lương, tiền công.",
        "answer": "Theo quy định tại **Điều 22 Luật Thuế Thu nhập cá nhân 2007 (sửa đổi, bổ sung 2012)**, Biểu thuế lũy tiến từng phần áp dụng đối với thu nhập từ tiền lương, tiền công của cá nhân cư trú bao gồm **07 bậc** như sau (tính trên phần *Thu nhập tính thuế* sau khi đã trừ đi các khoản giảm trừ):\n\n1. **Bậc 1:** Thu nhập tính thuế đến 5 triệu đồng/tháng -> Thuế suất **5%**\n2. **Bậc 2:** Trên 5 triệu đến 10 triệu đồng/tháng -> Thuế suất **10%**\n3. **Bậc 3:** Trên 10 triệu đến 18 triệu đồng/tháng -> Thuế suất **15%**\n4. **Bậc 4:** Trên 18 triệu đến 32 triệu đồng/tháng -> Thuế suất **20%**\n5. **Bậc 5:** Trên 32 triệu đến 52 triệu đồng/tháng -> Thuế suất **25%**\n6. **Bậc 6:** Trên 52 triệu đến 80 triệu đồng/tháng -> Thuế suất **30%**\n7. **Bậc 7:** Trên 80 triệu đồng/tháng -> Thuế suất **35%**\n\n**Cách tính thuế nhanh:** Cơ quan thuế có ban hành bảng hướng dẫn phương pháp tính thuế rút gọn theo cách: `Thuế TNCN phải nộp = Thu nhập tính thuế x Thuế suất tương ứng - Số tiền trừ lùi`.\n\n**Lưu ý:** Thu nhập tính thuế là thu nhập thực nhận trừ đi các khoản đóng bảo hiểm bắt buộc, quỹ hưu trí tự nguyện, và các khoản giảm trừ gia cảnh."
    },
    {
        "q": "Mức giảm trừ gia cảnh hiện hành là bao nhiêu?",
        "tool_query": "Nghị quyết 954/2020/UBTVQH14 mức giảm trừ gia cảnh",
        "doc_title": "Nghị quyết 954/2020/UBTVQH14",
        "doc_snippet": "Mức giảm trừ đối với đối tượng nộp thuế là 11 triệu đồng/tháng; mức giảm trừ đối với mỗi người phụ thuộc là 4,4 triệu đồng/tháng.",
        "answer": "Căn cứ **Điều 1 Nghị quyết số 954/2020/UBTVQH14** (có hiệu lực từ kỳ tính thuế năm 2020), mức giảm trừ gia cảnh khi tính thuế Thu nhập cá nhân (TNCN) từ tiền lương, tiền công được quy định cụ thể như sau:\n\n**1. Giảm trừ cho bản thân người nộp thuế:**\nMức giảm trừ đối với đối tượng nộp thuế là **11.000.000 đồng/tháng** (tương đương 132.000.000 đồng/năm).\n\n**2. Giảm trừ cho người phụ thuộc:**\nMức giảm trừ đối với mỗi người phụ thuộc là **4.400.000 đồng/tháng**.\n\n**Điều kiện tính giảm trừ người phụ thuộc:**\n- Người nộp thuế phải đã đăng ký thuế và được cấp mã số thuế.\n- Phải có hồ sơ chứng minh người phụ thuộc hợp lệ (ví dụ: Giấy khai sinh đối với con; CMND/CCCD và xác nhận thu nhập đối với cha mẹ hết tuổi lao động).\n- Mỗi người phụ thuộc chỉ được tính giảm trừ một lần vào một người nộp thuế trong năm tính thuế.\n\n**Khuyến nghị:** Đối với trường hợp có phát sinh nghĩa vụ nuôi dưỡng nhưng chưa đăng ký người phụ thuộc từ đầu năm, cá nhân vẫn có thể đăng ký bổ sung và được tính giảm trừ lùi lại từ tháng phát sinh nghĩa vụ nuôi dưỡng khi thực hiện quyết toán thuế năm."
    },
    {
        "q": "Thủ tục đăng ký người phụ thuộc để giảm trừ thuế TNCN cần những gì?",
        "tool_query": "Thông tư 111/2013/TT-BTC hồ sơ đăng ký người phụ thuộc",
        "doc_title": "Thông tư 111/2013/TT-BTC",
        "doc_snippet": "Hồ sơ đăng ký người phụ thuộc bao gồm Tờ khai đăng ký người phụ thuộc, Giấy khai sinh, CMND và các giấy tờ chứng minh quan hệ nuôi dưỡng.",
        "answer": "Theo quy định tại **Thông tư 111/2013/TT-BTC** và **Thông tư 80/2021/TT-BTC**, thủ tục đăng ký người phụ thuộc giảm trừ gia cảnh thuế TNCN được thực hiện như sau:\n\n**1. Hồ sơ chứng minh người phụ thuộc:**\n- **Đối với con:** Bản chụp Giấy khai sinh, CMND/CCCD (nếu có), Giấy xác nhận khuyết tật (nếu con khuyết tật), Giấy xác nhận đang đi học (nếu con từ 18 tuổi trở lên đang học Đại học/Cao đẳng và không có thu nhập hoặc thu nhập dưới 1 triệu đồng/tháng).\n- **Đối với vợ/chồng, cha mẹ:** Bản chụp CMND/CCCD, giấy tờ chứng minh mối quan hệ (Sổ hộ khẩu/Giấy chứng nhận kết hôn/Giấy khai sinh của NNT), giấy tờ chứng minh là người khuyết tật/hết tuổi lao động và không có thu nhập hoặc thu nhập bình quân tháng trong năm từ tất cả các nguồn không vượt quá 1.000.000 đồng.\n\n**2. Trình tự thực hiện:**\n- **Bước 1:** Cá nhân điền thông tin vào Mẫu 07/ĐK-NPT-TNCN và nộp hồ sơ chứng minh cho tổ chức trả thu nhập (Công ty) hoặc nộp trực tiếp cho Cơ quan thuế (nếu tự quyết toán).\n- **Bước 2:** Tổ chức trả thu nhập tổng hợp thông tin, nộp Mẫu 20-ĐK-TH-TCT qua cổng thông tin điện tử của Tổng cục Thuế để đăng ký cấp mã số thuế cho người phụ thuộc.\n\n**Lưu ý:** Hồ sơ chứng minh người phụ thuộc cá nhân phải nộp cho tổ chức trả thu nhập chậm nhất là 03 tháng kể từ ngày nộp tờ khai đăng ký người phụ thuộc. Tổ chức trả thu nhập có trách nhiệm lưu giữ và xuất trình khi Cơ quan thuế thanh tra."
    },

    # 4. Thuế TNDN — Chi phí được trừ
    {
        "q": "Các điều kiện cơ bản để một khoản chi phí được tính là chi phí hợp lý khi tính thuế TNDN?",
        "tool_query": "Thông tư 96/2015/TT-BTC điều kiện chi phí được trừ TNDN",
        "doc_title": "Thông tư 96/2015/TT-BTC",
        "doc_snippet": "Doanh nghiệp được trừ mọi khoản chi nếu đáp ứng 3 điều kiện: thực tế phát sinh, có hóa đơn hợp pháp, thanh toán không dùng tiền mặt (nếu từ 20 triệu).",
        "answer": "Căn cứ **Điều 4 Thông tư 96/2015/TT-BTC** (sửa đổi, bổ sung Điều 6 Thông tư 78/2014/TT-BTC), doanh nghiệp được trừ mọi khoản chi (được tính vào chi phí hợp lý khi xác định thu nhập chịu thuế TNDN) nếu đáp ứng đủ **03 điều kiện** sau:\n\n**1. Điều kiện về tính chất khoản chi:**\nKhoản chi thực tế phát sinh liên quan đến hoạt động sản xuất, kinh doanh của doanh nghiệp.\n\n**2. Điều kiện về hóa đơn, chứng từ:**\nKhoản chi có đủ hoá đơn, chứng từ hợp pháp theo quy định của pháp luật (Ví dụ: Hóa đơn điện tử hợp pháp, Phiếu xuất kho, Hợp đồng, Biên bản nghiệm thu...).\n\n**3. Điều kiện về thanh toán:**\nKhoản chi nếu có hoá đơn mua hàng hoá, dịch vụ từng lần có giá trị **từ 20 triệu đồng trở lên** (giá đã bao gồm thuế GTGT) khi thanh toán phải có chứng từ thanh toán không dùng tiền mặt (chuyển khoản qua ngân hàng).\n\n**Khuyến nghị:** Đối với các khoản chi mua hàng hóa nông sản, hải sản của người trực tiếp sản xuất không có hóa đơn, doanh nghiệp phải lập Bảng kê thu mua hàng hóa, dịch vụ (Mẫu 01/TNDN) kèm chứng từ thanh toán thì mới được tính vào chi phí hợp lý."
    },
    {
        "q": "Những khoản chi nào KHÔNG được tính vào chi phí được trừ khi tính thuế TNDN?",
        "tool_query": "Thông tư 96/2015/TT-BTC các khoản chi không được trừ TNDN",
        "doc_title": "Thông tư 96/2015/TT-BTC",
        "doc_snippet": "Các khoản chi không được trừ bao gồm: chi phí không đủ hóa đơn chứng từ, tiền lương không thực tế chi trả, các khoản tiền phạt vi phạm hành chính...",
        "answer": "Theo **Điều 4 Thông tư 96/2015/TT-BTC** liệt kê cụ thể 37 khoản chi **không được trừ** khi xác định thu nhập chịu thuế TNDN. Dưới đây là các khoản chi doanh nghiệp thường hay mắc phải nhất:\n\n**1. Chi phí không có hóa đơn, chứng từ hợp lệ:** \nChi phí phát sinh nhưng không có hóa đơn hợp pháp hoặc hóa đơn từ 20 triệu đồng trở lên không thanh toán qua ngân hàng.\n\n**2. Tiền lương, tiền công không thực tế chi trả:**\nChi phí tiền lương, tiền thưởng không được ghi cụ thể điều kiện được hưởng và mức được hưởng trong Hợp đồng lao động, Thỏa ước lao động tập thể hoặc Quy chế tài chính của công ty. Tiền lương đã hạch toán nhưng thực tế chưa chi trả cho người lao động cho đến thời hạn nộp hồ sơ quyết toán thuế.\n\n**3. Khấu hao tài sản cố định (TSCĐ) không đúng quy định:**\nKhấu hao đối với TSCĐ không phục vụ sản xuất kinh doanh, không có giấy tờ chứng minh quyền sở hữu, hoặc trích khấu hao vượt mức quy định của Bộ Tài chính.\n\n**4. Các khoản tiền phạt:**\nTiền phạt vi phạm hành chính như vi phạm luật giao thông, vi phạm chế độ đăng ký kinh doanh, vi phạm pháp luật về thuế (phạt chậm nộp, phạt kê khai sai).\n\n**Lưu ý:** Doanh nghiệp cần hạch toán loại trừ (bóc tách) các khoản chi phí không được trừ này tại chỉ tiêu [B4] trên Tờ khai quyết toán thuế TNDN năm (Mẫu 03/TNDN) để không làm ảnh hưởng đến số thuế phải nộp hợp pháp."
    },
    {
        "q": "Thuế suất thuế TNDN phổ thông hiện nay là bao nhiêu phần trăm?",
        "tool_query": "Luật Thuế TNDN sửa đổi thuế suất TNDN phổ thông",
        "doc_title": "Luật số 32/2013/QH13 sửa đổi Luật thuế TNDN",
        "doc_snippet": "Từ ngày 01 tháng 01 năm 2016, mức thuế suất thuế thu nhập doanh nghiệp phổ thông áp dụng là 20%.",
        "answer": "Căn cứ theo **Điều 10 Luật Thuế Thu nhập doanh nghiệp số 14/2008/QH12** (được sửa đổi, bổ sung bởi Luật số 32/2013/QH13 và Luật số 71/2014/QH13), mức thuế suất thuế TNDN được quy định như sau:\n\n**1. Thuế suất phổ thông:**\nKể từ ngày 01/01/2016 đến nay, mức thuế suất thuế TNDN phổ thông áp dụng cho hầu hết các doanh nghiệp là **20%**.\n\n**2. Thuế suất đặc thù cho ngành nghề khai thác tài nguyên:**\n- Thuế suất thuế TNDN đối với hoạt động tìm kiếm, thăm dò, khai thác dầu, khí và tài nguyên quý hiếm khác tại Việt Nam từ **32% đến 50%** phù hợp với từng dự án, từng cơ sở kinh doanh.\n\n**3. Thuế suất ưu đãi:**\nMột số doanh nghiệp hoạt động trong các lĩnh vực công nghệ cao, đầu tư tại vùng có điều kiện kinh tế xã hội đặc biệt khó khăn, hoặc hoạt động xã hội hóa (giáo dục, y tế, môi trường) có thể được áp dụng mức thuế suất ưu đãi là **10%, 15% hoặc 17%** tùy điều kiện cụ thể.\n\n**Khuyến nghị:** Kế toán cần xác định đúng hoạt động kinh doanh của công ty có thuộc diện được hưởng thuế suất ưu đãi hay không. Việc áp dụng sai thuế suất sẽ dẫn đến rủi ro bị truy thu thuế và phạt tiền chậm nộp rất lớn khi cơ quan thuế thanh tra."
    },

    # 5. Hóa đơn điện tử
    {
        "q": "Những đối tượng nào bắt buộc phải sử dụng hóa đơn điện tử?",
        "tool_query": "Nghị định 123/2020/NĐ-CP đối tượng áp dụng hóa đơn điện tử",
        "doc_title": "Nghị định 123/2020/NĐ-CP",
        "doc_snippet": "Từ ngày 01 tháng 7 năm 2022, 100% doanh nghiệp, tổ chức kinh tế, hộ kinh doanh, cá nhân kinh doanh phải sử dụng hóa đơn điện tử.",
        "answer": "Theo quy định tại **Điều 59 Nghị định 123/2020/NĐ-CP** và hướng dẫn tại **Thông tư 78/2021/TT-BTC** của Bộ Tài chính về hóa đơn, chứng từ:\n\nKể từ ngày **01/07/2022**, bắt buộc **100%** doanh nghiệp, tổ chức kinh tế, hộ kinh doanh và cá nhân kinh doanh có nộp thuế theo phương pháp kê khai phải chuyển đổi và sử dụng **Hóa đơn điện tử (HĐĐT)** (có mã hoặc không có mã của cơ quan thuế).\n\n**Cụ thể về phân loại áp dụng:**\n1. **HĐĐT có mã của cơ quan thuế:** Áp dụng cho hầu hết các doanh nghiệp, tổ chức kinh tế, hộ kinh doanh, cá nhân kinh doanh (trừ các trường hợp được dùng HĐĐT không có mã).\n2. **HĐĐT không có mã của cơ quan thuế:** Áp dụng cho doanh nghiệp kinh doanh ở các lĩnh vực: điện lực, xăng dầu, bưu chính viễn thông, nước sạch, tài chính tín dụng, bảo hiểm, y tế, kinh doanh thương mại điện tử, siêu thị, thương mại, vận tải... và các doanh nghiệp đã sử dụng HĐĐT có hệ thống phần mềm đáp ứng kết nối dữ liệu với cơ quan thuế.\n\n**Lưu ý:** Việc sử dụng hóa đơn giấy đã chính thức chấm dứt. Doanh nghiệp cần lựa chọn tổ chức cung cấp dịch vụ hóa đơn điện tử (T-VAN) uy tín để tích hợp chữ ký số và hệ thống quản trị, đảm bảo việc xuất hóa đơn diễn ra thông suốt."
    },
    {
        "q": "Khi bán hàng hóa, cung cấp dịch vụ, thời điểm nào thì bắt buộc phải xuất hóa đơn?",
        "tool_query": "Nghị định 123/2020/NĐ-CP thời điểm lập hóa đơn",
        "doc_title": "Nghị định 123/2020/NĐ-CP",
        "doc_snippet": "Thời điểm lập hóa đơn là thời điểm chuyển giao quyền sở hữu hàng hóa, hoặc hoàn thành việc cung cấp dịch vụ, bất kể đã thu tiền hay chưa.",
        "answer": "Căn cứ **Điều 9 Nghị định 123/2020/NĐ-CP**, thời điểm lập hóa đơn được quy định rất nghiêm ngặt đối với từng loại hình kinh doanh:\n\n**1. Đối với bán hàng hóa:**\nThời điểm lập hóa đơn là thời điểm **chuyển giao quyền sở hữu hoặc quyền sử dụng hàng hóa** cho người mua, không phân biệt đã thu được tiền hay chưa thu được tiền.\n\n**2. Đối với cung cấp dịch vụ:**\nThời điểm lập hóa đơn là thời điểm **hoàn thành việc cung cấp dịch vụ** không phân biệt đã thu được tiền hay chưa thu được tiền. \n*Đặc biệt:* Trường hợp người cung cấp dịch vụ có thu tiền trước hoặc trong khi cung cấp dịch vụ thì thời điểm lập hóa đơn là thời điểm thu tiền (trừ trường hợp thu tiền đặt cọc hoặc tạm ứng để bảo đảm thực hiện hợp đồng).\n\n**3. Đối với hoạt động xây dựng, lắp đặt:**\nThời điểm lập hóa đơn là thời điểm nghiệm thu, bàn giao công trình, hạng mục công trình, khối lượng xây dựng, lắp đặt hoàn thành, không phân biệt đã thu được tiền hay chưa thu được tiền.\n\n**Cảnh báo rủi ro:** Hành vi lập hóa đơn sai thời điểm (xuất lùi ngày, xuất muộn) có thể bị phạt tiền từ **4.000.000 đồng đến 8.000.000 đồng** theo Điều 24 Nghị định 125/2020/NĐ-CP."
    },
    {
        "q": "Hóa đơn điện tử đã gửi cơ quan thuế cấp mã nhưng phát hiện sai sót thì xử lý như thế nào?",
        "tool_query": "Nghị định 123/2020/NĐ-CP xử lý hóa đơn điện tử sai sót",
        "doc_title": "Nghị định 123/2020/NĐ-CP",
        "doc_snippet": "Người bán gửi Thông báo sai sót Mẫu 04/SS-HĐĐT, sau đó lập hóa đơn điện tử mới (thay thế hoặc điều chỉnh) gửi cơ quan thuế cấp lại mã.",
        "answer": "Theo quy định tại **Điều 19 Nghị định 123/2020/NĐ-CP**, quy trình xử lý hóa đơn điện tử (HĐĐT) đã được cấp mã có sai sót được thực hiện theo 02 trường hợp sau:\n\n**Trường hợp 1: Hóa đơn có sai sót nhưng CHƯA gửi cho người mua**\n- Người bán thực hiện gửi Thông báo sai sót (Mẫu số 04/SS-HĐĐT) cho cơ quan thuế để đề nghị HỦY hóa đơn đã lập.\n- Sau đó, lập hóa đơn điện tử mới, ký số và gửi cơ quan thuế để cấp mã mới và gửi cho người mua.\n\n**Trường hợp 2: Hóa đơn có sai sót và ĐÃ gửi cho người mua**\n- **Nếu chỉ sai tên, địa chỉ người mua (không sai MST và các chỉ tiêu khác):** Người bán chỉ cần thông báo cho người mua về việc sai sót và gửi Mẫu 04/SS-HĐĐT cho cơ quan thuế. Không phải lập lại hóa đơn.\n- **Nếu sai mã số thuế, sai số tiền, sai thuế suất, tiền thuế, quy cách hàng hóa:** \nNgười bán và người mua lập biên bản thỏa thuận ghi rõ sai sót. Sau đó người bán có 2 lựa chọn:\n  + **Lựa chọn 1:** Lập HĐĐT điều chỉnh (ghi rõ \"Điều chỉnh cho hóa đơn số..., ký hiệu..., ngày...\").\n  + **Lựa chọn 2:** Lập HĐĐT thay thế (ghi rõ \"Thay thế cho hóa đơn số..., ký hiệu..., ngày...\").\n\n**Khuyến nghị:** Việc xuất hóa đơn điều chỉnh thường dễ gây nhầm lẫn khi lên tờ khai thuế nếu không am hiểu nghiệp vụ (điều chỉnh tăng/giảm). Khuyến nghị ưu tiên dùng phương thức lập **Hóa đơn Thay thế** để dễ theo dõi sổ sách."
    },
]
