LEGAL_DEEP_DATA_NEW_4 = [
    # 13. Quản lý thuế thương mại điện tử
    {
        "q": "Nhà cung cấp ở nước ngoài không có văn phòng tại VN bán hàng thì khai thuế thế nào?",
        "tool_query": "Thông tư 80/2021/TT-BTC thuế nhà cung cấp nước ngoài TMĐT",
        "doc_title": "Thông tư 80/2021/TT-BTC",
        "doc_snippet": "Nhà cung cấp ở nước ngoài không có cơ sở thường trú tại Việt Nam thực hiện đăng ký thuế, khai thuế, nộp thuế trực tiếp thông qua Cổng thông tin điện tử của Tổng cục Thuế.",
        "answer": "Căn cứ theo **Điều 76, 77, 78 Thông tư 80/2021/TT-BTC** hướng dẫn quản lý thuế đối với nhà cung cấp ở nước ngoài (NCCNN) không có cơ sở thường trú tại Việt Nam có hoạt động kinh doanh thương mại điện tử, kinh doanh dựa trên nền tảng số tại Việt Nam (VD: Facebook, Google, Netflix, Tiktok...):\n\n**1. Nghĩa vụ đăng ký và nộp thuế:**\nNCCNN có nghĩa vụ trực tiếp đăng ký thuế, khai thuế và nộp thuế điện tử thông qua **Cổng thông tin điện tử dành riêng cho nhà cung cấp ở nước ngoài** của Tổng cục Thuế Việt Nam.\n\n**2. Khai thuế và nộp thuế thay:**\nTrường hợp NCCNN không trực tiếp đăng ký, khai thuế thì:\n- Các ngân hàng thương mại, tổ chức cung ứng dịch vụ trung gian thanh toán có trách nhiệm khấu trừ, nộp thay thuế.\n- Tổ chức, cá nhân tại Việt Nam mua hàng hóa, dịch vụ của NCCNN có trách nhiệm kê khai, khấu trừ và nộp thay thuế nhà thầu (theo quy định tại Thông tư 103/2014/TT-BTC).\n\n**Khuyến nghị:** Đối với doanh nghiệp Việt Nam chạy quảng cáo trên Facebook, Google, nếu các tập đoàn này đã đăng ký nộp thuế trực tiếp tại Việt Nam thì doanh nghiệp không cần khấu trừ thuế nhà thầu nữa, chỉ cần hạch toán chi phí hợp lý bằng hóa đơn/chứng từ do Facebook/Google xuất."
    },
    {
        "q": "Máy tính tiền có kết nối dữ liệu với cơ quan thuế là gì?",
        "tool_query": "Thông tư 78/2021/TT-BTC hóa đơn từ máy tính tiền",
        "doc_title": "Thông tư 78/2021/TT-BTC",
        "doc_snippet": "Hóa đơn điện tử khởi tạo từ máy tính tiền có kết nối chuyển dữ liệu với cơ quan thuế áp dụng cho các cơ sở kinh doanh dịch vụ ăn uống, siêu thị, bán lẻ thuốc...",
        "answer": "Theo **Điều 8 Thông tư 78/2021/TT-BTC** và **Nghị định 123/2020/NĐ-CP**, Hóa đơn điện tử (HĐĐT) khởi tạo từ máy tính tiền là hình thức xuất hóa đơn thế hệ mới dành riêng cho các ngành nghề bán lẻ thường xuyên:\n\n**1. Đối tượng áp dụng:**\nDoanh nghiệp, hộ kinh doanh nộp thuế theo phương pháp kê khai có hoạt động cung cấp hàng hoá, dịch vụ trực tiếp đến người tiêu dùng như: Trung tâm thương mại, siêu thị, kinh doanh dịch vụ ăn uống (nhà hàng, quán cafe), bán lẻ thuốc tân dược, dịch vụ vui chơi giải trí.\n\n**2. Lợi ích so với HĐĐT thông thường:**\n- Người bán có thể chủ động xuất hóa đơn 24/7 một cách nhanh chóng mà không cần ký số điện tử trên từng tờ hóa đơn.\n- Có thể xuất hóa đơn ngay cả khi mất kết nối mạng lưới internet tạm thời.\n- Người mua hàng nhận hóa đơn có mã của cơ quan thuế ngay lập tức để tham gia chương trình \"Hóa đơn may mắn\" trúng thưởng.\n\n**Khuyến nghị:** Việc triển khai HĐĐT từ máy tính tiền đang được Tổng cục Thuế đẩy mạnh bắt buộc đối với lĩnh vực nhà hàng, ăn uống và vàng bạc đá quý nhằm chống thất thu thuế doanh thu bán lẻ."
    },
    {
        "q": "Người mua hàng trên mạng nếu không lấy hóa đơn thì người bán có phải xuất không?",
        "tool_query": "Nghị định 123/2020/NĐ-CP xuất hóa đơn khi người mua không lấy",
        "doc_title": "Nghị định 123/2020/NĐ-CP",
        "doc_snippet": "Trường hợp người mua không lấy hóa đơn hoặc không cung cấp tên, địa chỉ, mã số thuế thì người bán vẫn phải lập hóa đơn điện tử.",
        "answer": "Căn cứ **Khoản 7 Điều 10 Nghị định 123/2020/NĐ-CP** quy định về lập hóa đơn:\n\nKhi bán hàng hóa, cung cấp dịch vụ, kể cả bán hàng trực tuyến (online) hoặc bán lẻ trực tiếp, nếu người mua không lấy hóa đơn hoặc không cung cấp thông tin (Tên, Địa chỉ, Mã số thuế) thì **người bán VẪN BẮT BUỘC PHẢI LẬP hóa đơn điện tử**.\n\n**Cách thức lập hóa đơn trong trường hợp này:**\n- Người bán vẫn xuất hóa đơn với đầy đủ thông tin hàng hóa, số tiền.\n- Tại chỉ tiêu thông tin người mua: Ghi rõ **\"người mua không lấy hóa đơn\"** hoặc **\"người mua không cung cấp tên, địa chỉ, mã số thuế\"**.\n- Đối với người bán lẻ hàng hóa, dịch vụ ăn uống: Có thể lập hóa đơn điện tử khởi tạo từ máy tính tiền hoặc gom bảng kê cuối ngày để xuất 1 hóa đơn tổng hợp (tùy thuộc ngành nghề được phép).\n\n**Cảnh báo rủi ro:** Nếu người bán cố tình không xuất hóa đơn với lý do \"khách không yêu cầu\" nhằm giấu doanh thu, hành vi này sẽ bị phạt tiền từ **10.000.000 đồng đến 20.000.000 đồng** theo Điều 24 Nghị định 125/2020/NĐ-CP, đồng thời có thể bị truy cứu tội trốn thuế."
    },

    # 14. Thuế GTGT hàng nhập khẩu & Thuế xuất nhập khẩu
    {
        "q": "Khi nào thì được miễn thuế nhập khẩu đối với hàng hóa gia công?",
        "tool_query": "Nghị định 134/2016/NĐ-CP miễn thuế nhập khẩu gia công",
        "doc_title": "Nghị định 134/2016/NĐ-CP",
        "doc_snippet": "Hàng hóa nhập khẩu để gia công cho phía nước ngoài được miễn thuế nhập khẩu, bao gồm nguyên liệu, bán thành phẩm, máy móc thiết bị phục vụ trực tiếp cho gia công.",
        "answer": "Theo quy định tại **Điều 10 Nghị định 134/2016/NĐ-CP** (được sửa đổi bổ sung bởi Nghị định 18/2021/NĐ-CP) hướng dẫn Luật Thuế Xuất khẩu, thuế Nhập khẩu:\n\nHàng hóa nhập khẩu để gia công cho phía nước ngoài được **miễn thuế nhập khẩu**, bao gồm các điều kiện và danh mục sau:\n\n**1. Các loại hàng hóa được miễn thuế:**\n- Nguyên liệu, bán thành phẩm, vật tư nhập khẩu phục vụ trực tiếp cho hợp đồng gia công.\n- Linh kiện, phụ tùng nhập khẩu để lắp ráp, sửa chữa máy móc thiết bị.\n- Máy móc, thiết bị nhập khẩu theo thỏa thuận tại hợp đồng gia công để trực tiếp thực hiện gia công.\n- Sản phẩm gia công hoàn chỉnh nhập khẩu để gắn vào sản phẩm gia công.\n\n**2. Điều kiện để được miễn thuế:**\n- Doanh nghiệp phải có cơ sở gia công, cơ sở sản xuất hàng hóa tại Việt Nam và có quyền sở hữu/quyền sử dụng máy móc thiết bị tại cơ sở sản xuất.\n- Phải thông báo cơ sở gia công và hợp đồng gia công cho cơ quan hải quan trước khi thực hiện nhập khẩu.\n- Hàng hóa sau khi gia công phải được **xuất khẩu trả lại** cho phía nước ngoài theo thời hạn hợp đồng.\n\n**Lưu ý:** Nếu sau khi nhập khẩu miễn thuế mà doanh nghiệp tự ý đem tiêu thụ nội địa (chuyển đổi mục đích sử dụng) mà không khai báo hải quan và nộp thuế, sẽ bị xử lý hình sự về tội buôn lậu hoặc trốn thuế."
    },
    {
        "q": "Thuế GTGT hàng nhập khẩu tính trên giá nào?",
        "tool_query": "Luật Thuế GTGT giá tính thuế hàng nhập khẩu",
        "doc_title": "Luật Thuế Giá trị gia tăng 2008 (sửa đổi 2013)",
        "doc_snippet": "Giá tính thuế GTGT đối với hàng hóa nhập khẩu là giá nhập tại cửa khẩu cộng (+) với thuế nhập khẩu, cộng (+) với thuế tiêu thụ đặc biệt, cộng (+) với thuế bảo vệ môi trường (nếu có).",
        "answer": "Căn cứ **Khoản 2 Điều 7 Luật Thuế Giá trị gia tăng 2008 (sửa đổi bổ sung)**, giá tính thuế GTGT đối với hàng hóa nhập khẩu không chỉ là giá mua của lô hàng mà là giá trị đã bao gồm các loại thuế ở khâu nhập khẩu. Cụ thể công thức tính như sau:\n\n**Giá tính thuế GTGT hàng nhập khẩu = Giá trị tính thuế Nhập khẩu (CIF) + Thuế Nhập khẩu + Thuế Tiêu thụ đặc biệt + Thuế Bảo vệ môi trường (nếu có).**\n\nTrong đó:\n- **Giá trị tính thuế nhập khẩu (thường là giá CIF):** Bao gồm trị giá thực tế của hàng hóa + chi phí vận tải quốc tế + phí bảo hiểm quốc tế tính đến cửa khẩu nhập đầu tiên của Việt Nam.\n- **Thuế Nhập khẩu:** Tính theo biểu thuế XNK hiện hành.\n\n`Số thuế GTGT khâu nhập khẩu phải nộp = Giá tính thuế GTGT x Thuế suất thuế GTGT` (thường là 8% hoặc 10%).\n\n**Khuyến nghị:** Khoản thuế GTGT khâu nhập khẩu doanh nghiệp nộp tại Hải quan sẽ được dùng làm căn cứ để kê khai khấu trừ thuế GTGT đầu vào tại Cơ quan thuế nội địa. Kế toán cần lưu giữ Giấy nộp tiền vào ngân sách nhà nước làm chứng từ khấu trừ."
    },
    {
        "q": "Hàng nhập khẩu sau đó xuất trả lại chủ hàng nước ngoài có được hoàn thuế không?",
        "tool_query": "Nghị định 134/2016/NĐ-CP hoàn thuế hàng nhập khẩu tái xuất",
        "doc_title": "Nghị định 134/2016/NĐ-CP",
        "doc_snippet": "Hàng hóa nhập khẩu đã nộp thuế nhập khẩu nhưng phải tái xuất được hoàn thuế nhập khẩu và không phải nộp thuế xuất khẩu.",
        "answer": "Theo **Điều 34 Nghị định 134/2016/NĐ-CP** (sửa đổi, bổ sung bởi Nghị định 18/2021/NĐ-CP), việc xử lý thuế đối với hàng hóa nhập khẩu sau đó tái xuất được quy định như sau:\n\n**1. Về Thuế Nhập khẩu:**\nHàng hóa nhập khẩu đã nộp thuế nhập khẩu nhưng phải xuất trả lại (tái xuất) cho chủ hàng nước ngoài hoặc xuất sang nước thứ ba thì **được hoàn lại số thuế nhập khẩu đã nộp**.\n*Điều kiện:* Hàng hóa tái xuất chưa qua sử dụng, gia công, chế biến tại Việt Nam và việc tái xuất phải được thực hiện bởi chính người nhập khẩu ban đầu.\n\n**2. Về Thuế Xuất khẩu:**\nHàng hóa nhập khẩu khi xuất trả lại (tái xuất) sẽ **không phải nộp thuế xuất khẩu**.\n\n**3. Về Thuế GTGT khâu nhập khẩu:**\n- Tại Hải quan: Cơ quan hải quan KHÔNG hoàn trả thuế GTGT khâu nhập khẩu đã nộp.\n- Tại Cơ quan Thuế nội địa: Số thuế GTGT khâu nhập khẩu mà doanh nghiệp đã nộp sẽ được tính vào thuế GTGT đầu vào được khấu trừ, và doanh nghiệp sẽ khai báo để bù trừ hoặc xin hoàn thuế GTGT tại cơ quan thuế quản lý trực tiếp.\n\n**Lưu ý:** Hồ sơ hoàn thuế nhập khẩu cần nộp tại Chi cục Hải quan nơi đã làm thủ tục nhập khẩu lô hàng đó."
    },

    # 15. Quyết toán thuế TNCN
    {
        "q": "Cá nhân có nhiều nguồn thu nhập thì phải tự quyết toán thuế TNCN ở đâu?",
        "tool_query": "Thông tư 80/2021/TT-BTC nơi nộp hồ sơ quyết toán thuế TNCN",
        "doc_title": "Thông tư 80/2021/TT-BTC",
        "doc_snippet": "Cá nhân có thu nhập từ 2 nơi trở lên trực tiếp quyết toán thuế với cơ quan thuế nơi cư trú hoặc nơi có nguồn thu nhập lớn nhất.",
        "answer": "Theo hướng dẫn tại **Khoản 8 Điều 11 Nghị định 126/2020/NĐ-CP** và **Thông tư 80/2021/TT-BTC**, cá nhân có thu nhập từ tiền lương, tiền công từ hai nơi trở lên nếu có phát sinh số thuế phải nộp thêm hoặc có số thuế nộp thừa xin hoàn thì phải trực tiếp quyết toán thuế với cơ quan thuế. Nơi nộp hồ sơ được quy định như sau:\n\n**1. Nếu đã tính giảm trừ gia cảnh tại một tổ chức chi trả thu nhập:**\nCá nhân nộp hồ sơ quyết toán thuế tại cơ quan thuế quản lý trực tiếp tổ chức chi trả thu nhập đó.\n\n**2. Nếu chưa tính giảm trừ gia cảnh tại bất kỳ nơi nào:**\nCá nhân nộp hồ sơ quyết toán tại Chi cục Thuế nơi cá nhân cư trú (nơi đăng ký thường trú hoặc tạm trú).\n\n**3. Trường hợp có thay đổi nơi làm việc trong năm:**\n- Nếu thời điểm quyết toán cá nhân đang làm việc tại một tổ chức: Nộp tại cơ quan thuế quản lý tổ chức đó.\n- Nếu thời điểm quyết toán cá nhân đã nghỉ việc và không làm việc ở đâu: Nộp tại cơ quan thuế nơi cư trú.\n\n**Khuyến nghị:** Hiện nay Tổng cục Thuế khuyến khích cá nhân trực tiếp quyết toán online qua ứng dụng eTax Mobile hoặc website *thuedientu.gdt.gov.vn*. Hệ thống sẽ tự động xác định cơ quan thuế tiếp nhận hồ sơ dựa trên thông tin kê khai, giúp tiết kiệm thời gian đi lại."
    },
    {
        "q": "Trường hợp nào được ủy quyền cho Công ty quyết toán thuế TNCN thay?",
        "tool_query": "Nghị định 126/2020/NĐ-CP ủy quyền quyết toán thuế TNCN",
        "doc_title": "Nghị định 126/2020/NĐ-CP",
        "doc_snippet": "Cá nhân chỉ có thu nhập từ tiền lương, tiền công ký hợp đồng lao động từ 03 tháng trở lên tại một nơi và thực tế đang làm việc tại đó vào thời điểm quyết toán thuế được ủy quyền quyết toán.",
        "answer": "Căn cứ **Nghị định 126/2020/NĐ-CP** và công văn hướng dẫn quyết toán thuế hàng năm của Tổng cục Thuế, cá nhân có thu nhập từ tiền lương, tiền công được ủy quyền cho tổ chức trả thu nhập (Công ty) quyết toán thuế thay trong các trường hợp sau:\n\n**1. Làm việc duy nhất tại 1 nơi:**\nCá nhân ký hợp đồng lao động từ 03 tháng trở lên tại một tổ chức và thực tế đang làm việc tại tổ chức đó vào thời điểm tổ chức thực hiện quyết toán thuế (kể cả trường hợp không làm việc đủ 12 tháng trong năm).\n\n**2. Có thêm thu nhập vãng lai mức thấp:**\nCá nhân làm việc 1 nơi chính (như điều kiện 1) và có thu nhập vãng lai ở các nơi khác bình quân tháng trong năm **không quá 10 triệu đồng**, ĐÃ ĐƯỢC tổ chức trả thu nhập **khấu trừ thuế 10%**.\n*(Trường hợp này nếu cá nhân không có yêu cầu quyết toán đối với phần thu nhập vãng lai thì được ủy quyền cho Công ty nơi làm chính quyết toán thay đối với phần thu nhập tại nơi làm chính).*\n\n**3. Trường hợp luân chuyển nội bộ:**\nCá nhân được điều chuyển từ tổ chức cũ sang tổ chức mới trong trường hợp tổ chức cũ thực hiện sáp nhập, hợp nhất, chia, tách, chuyển đổi loại hình hoặc điều chuyển trong cùng hệ thống tập đoàn.\n\n**Lưu ý:** Nếu cá nhân có số thuế phải nộp thêm sau quyết toán từ **50.000 đồng trở xuống** thì được miễn nộp khoản này và không bắt buộc phải thực hiện nộp hồ sơ quyết toán."
    },
    {
        "q": "Phạt bao nhiêu nếu nộp chậm hồ sơ quyết toán thuế TNCN?",
        "tool_query": "Nghị định 125/2020/NĐ-CP phạt nộp chậm quyết toán TNCN",
        "doc_title": "Nghị định 125/2020/NĐ-CP",
        "doc_snippet": "Chậm nộp hồ sơ quyết toán thuế từ 1 đến 90 ngày bị phạt tiền từ 2 đến 15 triệu đồng. Quá 90 ngày có phát sinh thuế phải nộp phạt từ 15 đến 25 triệu.",
        "answer": "Theo **Điều 13 Nghị định 125/2020/NĐ-CP**, mức phạt đối với hành vi chậm nộp hồ sơ khai quyết toán thuế TNCN (thời hạn nộp đối với cá nhân tự quyết toán là ngày cuối cùng của tháng thứ 4 kể từ ngày kết thúc năm dương lịch - tức 04/05/2024 đối với kỳ tính thuế 2023) được quy định như sau:\n\n**1. Phát sinh số thuế PHẢI NỘP THÊM:**\n- Chậm nộp từ 01 - 30 ngày: Phạt từ 2.000.000đ đến 5.000.000đ.\n- Chậm nộp từ 31 - 60 ngày: Phạt từ 5.000.000đ đến 8.000.000đ.\n- Chậm nộp từ 61 - 90 ngày: Phạt từ 8.000.000đ đến 15.000.000đ.\n- Chậm nộp trên 90 ngày: Phạt từ **15.000.000đ đến 25.000.000đ** (và áp dụng biện pháp truy thu, phạt chậm nộp 0,03%/ngày đối với số tiền nợ thuế gốc).\n\n**2. Phát sinh số thuế NỘP THỪA (có yêu cầu hoàn thuế):**\nTrường hợp cá nhân nộp thừa tiền thuế và có yêu cầu hoàn thuế TNCN thì việc nộp hồ sơ quyết toán thuế quá thời hạn quy định **KHÔNG bị xử phạt** vi phạm hành chính. Cá nhân có thể nộp hồ sơ hoàn thuế vào bất kỳ thời điểm nào.\n\n**Khuyến nghị:** Nếu cá nhân tính toán thấy mình được hoàn thuế thì không cần lo lắng về thời hạn nộp hồ sơ (không bị phạt). Nhưng nếu phát sinh số thuế nộp thêm, cá nhân bắt buộc phải nộp đúng hạn để tránh mức phạt hành chính rất nặng."
    }
]
